// ─────────────────────────────────────────────────────────────────────────────
//  flatFormat.ts — serializer for ".flat" ASSETS ("modern SWF" RFC, step P0).
//
//  A `.flat` library = SYMBOLS as readable TEXT (generated by the editor, re-readable/editable by
//  hand). The substance (geometry) is expressed as an SVG `d` path. Model <-> text, PURE, round-trip
//  tested at the MODEL level (ids regenerated at parse -> we compare the structure, not the ids).
//
//  Covered (P0a+P0b1): symbol · layer · region (path/fill/stroke/nofill/opacity) · group ·
//  instance (by symbol name + instance name) · text · image · poseable attributes
//  (opacity/pivot/tint/filters/expressions).
//  Coming (P0b2): timeline/cels (poses, substance, tween/morph, easing, spin) · sound.
//
//  PURE module (no DOM).
// ─────────────────────────────────────────────────────────────────────────────
import type { Asset, Doc, Folder, Group, Image, Instance, InstancePlayback, Item, Layer, ParamDef, Region, StateAnchor, StateMachine, SymbolDef, Text } from '@flatkit/types'
import type { Path } from './path'
import { normalizeClosedForText } from './path'
import type { Paint, Stop, Tint } from './paint'
import type { Filter } from './filters'
import type { Transform } from './transform'
import type { Cel, Pose } from './cel'
import type { Interaction } from './actions'
import type { BlendMode, Interactor } from '@flatkit/types'
import { EXPR_CHANNELS, type Easing, type ExprChannel, type SoundClip, type Timeline } from './timeline'
import { parsePathData, circlePath, ellipsePath, rectPath } from './svgPath'
import { compileExpr, evalExpr, exprScope } from './expr'
import { isGroup, isInstance, isText, isImage, isPoseable, folderPath } from './layers'
import { itemBoundsByName } from './groups'
import type { BBox } from './bbox'
import { printUnits, parseUnits, type Diagnostic } from './dsl'
import { timelineToUnits, unitsToTimeline, objectToUnits, unitsToObject, functionsToUnits, unitsToFunctions } from './scriptDoc'

let _id = 0
const uid = (p: string) => `${p}${(_id++).toString(36)}`
const n = (v: number) => {
  const r = Math.round(v * 100) / 100
  return Object.is(r, -0) ? '0' : String(r)
}
/** Value of a program variable: number, or array (uniform -> `fill(n,v)`, otherwise `[…]`). */
const printVarValue = (v: number | number[]): string => {
  if (!Array.isArray(v)) return n(v)
  if (v.length >= 2 && v.every((x) => x === v[0])) return `fill(${v.length}, ${n(v[0])})`
  return `[${v.map(n).join(', ')}]`
}

// ── Geometry: Path → SVG `d` attribute (inverse of parsePathData). ────────────
export function pathToData(path: Path): string {
  const out: string[] = []
  for (const sp of path.subpaths) {
    const segs = sp.segments
    if (!segs.length) continue
    out.push(`M${n(segs[0].anchor.x)} ${n(segs[0].anchor.y)}`)
    const edges = sp.closed ? segs.length : segs.length - 1
    for (let i = 0; i < edges; i++) {
      const a = segs[i]
      const b = segs[(i + 1) % segs.length]
      const isClosingEdge = sp.closed && i === edges - 1
      const straight = !a.outHandle && !b.inHandle
      if (isClosingEdge && straight) break // `Z` closes with a straight line -> no need to make it explicit
      if (straight) out.push(`L${n(b.anchor.x)} ${n(b.anchor.y)}`)
      else {
        const c1 = a.outHandle ?? a.anchor
        const c2 = b.inHandle ?? b.anchor
        out.push(`C${n(c1.x)} ${n(c1.y)} ${n(c2.x)} ${n(c2.y)} ${n(b.anchor.x)} ${n(b.anchor.y)}`)
      }
    }
    if (sp.closed) out.push('Z')
  }
  return out.join('')
}

// ── Paint ──────────────────────────────────────────────────────────────────────
const printStop = (s: Stop) => (s.param ? `${n(s.offset)}:${s.param}${s.alpha != null ? `@${n(s.alpha)}` : ''}` : `${n(s.offset)}:${s.color}`)
const printStops = (stops: Stop[]) => stops.map(printStop).join(', ')
function printPaint(p: Paint): string {
  if (p.type === 'solid') return p.color
  if (p.type === 'linear') return `linear(${n(p.angle)}, ${printStops(p.stops)})`
  return `radial(${n(p.cx)}, ${n(p.cy)}, ${n(p.r)}, ${printStops(p.stops)})`
}
const paintColor = (p: Paint): string => (p.type === 'solid' ? p.color : (p.stops[0]?.color ?? '#000000'))

// ── Filters ──────────────────────────────────────────────────────────────────
function printFilter(f: Filter): string {
  if (f.type === 'blur') return `filter blur ${n(f.radius)}`
  if (f.type === 'shadow') return `filter shadow ${n(f.dx)} ${n(f.dy)} ${n(f.blur)} ${f.color}`
  if (f.type === 'glow') return `filter glow ${n(f.blur)} ${f.color}`
  return `filter adjust ${n(f.brightness ?? 1)} ${n(f.contrast ?? 1)} ${n(f.saturate ?? 1)} ${n(f.hue ?? 0)}`
}

// ── Transform: `at x,y` (translation) or `matrix(a,b,c,d,e,f)`. ────────────────
const isTranslate = (t: Transform) => t.a === 1 && t.b === 0 && t.c === 0 && t.d === 1
function printTransform(t: Transform): string {
  if (t.e === 0 && t.f === 0 && isTranslate(t)) return ''
  if (isTranslate(t)) return ` at ${n(t.e)},${n(t.f)}`
  return ` matrix(${n(t.a)},${n(t.b)},${n(t.c)},${n(t.d)},${n(t.e)},${n(t.f)})`
}

// ── Poseable attributes (opacity, pivot, tint, filters, expressions). ─────────
// `withExpr`: include the expressions? YES for a `.flat` asset (internal animation); NO for a
// `.flatink` program (there expressions are BEHAVIOR -> `object` block, not the composition).
type Poseable = Group | Instance | Text | Image
function printPoseAttrs(it: Poseable, withExpr: boolean): string {
  let s = ''
  if (it.opacity != null && it.opacity < 1) s += ` opacity ${n(it.opacity)}`
  if (it.noHit) s += ' nohit'
  if (it.pivot) s += ` pivot ${n(it.pivot.x)},${n(it.pivot.y)}`
  if (it.tint && it.tint.amount > 0) s += ` tint ${it.tint.param ?? it.tint.color} ${n(it.tint.amount)}`
  if (it.blend) s += ` blend ${it.blend}`
  if ('hitbox' in it && it.hitbox) s += ` hitbox ${n(it.hitbox.w)} ${n(it.hitbox.h)}`
  if ('clip' in it && it.clip) s += ` clip ${n(it.clip.x)} ${n(it.clip.y)} ${n(it.clip.w)} ${n(it.clip.h)}`
  if (it.filters) for (const f of it.filters) s += ' ' + printFilter(f)
  // Inlined channel expressions (`.flat`) — on ALL poseable leaves (group/instance/text/image).
  if (withExpr && it.expressions) for (const ch of EXPR_CHANNELS) { const ex = it.expressions[ch]; if (ex) s += ` expr ${ch} ${q(ex)}` }
  return s
}

// ── Printing (model → text) ────────────────────────────────────────────────────
const IND = '  '
const q = (s: string) => `"${s.replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/"/g, '\\"')}"`

type Ctx = { symName: (id: string) => string; inlineExpr: boolean; folderPath?: (id: string) => string }

function printRegion(r: Region, d: string): string {
  let s = `path "${d}"`
  if (r.name) s += ` as ${q(r.name)}` // stable name (addressable, e.g. `text … along "<id>"`)
  if (r.noFill) s += ' nofill'
  else if (r.fillParam) s += ` fill ${r.fillParam}` // fill bound to a symbol color param
  else s += ` fill ${printPaint(r.paint ?? { type: 'solid', color: r.color })}`
  if (r.stroke) {
    s += ` stroke ${r.strokeParam ?? printPaint(r.stroke.paint)} ${n(r.stroke.width)}` // param ref or literal paint
    if (r.stroke.cap) s += ` cap ${r.stroke.cap}`
    if (r.stroke.join) s += ` join ${r.stroke.join}`
    if (r.stroke.miterLimit != null) s += ` miter ${n(r.stroke.miterLimit)}`
    if (r.stroke.dash?.length) s += ` dash ${r.stroke.dash.map(n).join(',')}`
  }
  if (r.opacity != null && r.opacity < 1) s += ` opacity ${n(r.opacity)}`
  if (r.filters) for (const f of r.filters) s += ' ' + printFilter(f)
  if (r.noHit) s += ' nohit'
  return s
}

// Stable id of a Text item, set by the author via `as "<id>"` (referenced by text("…") on the DSL side /
// by the Moiki host). Same grammar as `send` event names: letter/"_" then -_alnum, 64 max.
const TEXT_ID = /^[A-Za-z_][A-Za-z0-9_-]{0,63}$/

function printText(t: Text, withExpr: boolean): string {
  // `as` printed only if the author set the id explicitly (flag set at parse) — no guessing about the form.
  const asId = t.idExplicit ? ` as ${q(t.id)}` : ''
  // `along "<ref>"` / `along path "<d>"` replaces the `at`/transform clause (text-on-path). start/side/spacing
  // printed only when non-default (`start 0`, `side over`, `spacing 0` are implicit).
  const tp = t.textPath
  let place: string
  if (tp?.ref) place = ` along ${q(tp.ref)}`
  else if (tp) place = ` along path ${q(pathToData(tp.path))}`
  else place = printTransform(t.transform)
  if (tp) {
    if (tp.startExpr) place += ` start ${q(tp.startExpr)}` // animated (marquee); else literal offset
    else if (tp.start) place += ` start ${n(tp.start)}`
    if (tp.side === 'under') place += ' side under'
    if (tp.spacingExpr) place += ` spacing ${q(tp.spacingExpr)}` // animated (eased tracking); else literal px
    else if (tp.spacing) place += ` spacing ${n(tp.spacing)}`
  }
  let s = `text ${q(t.content)}${asId}${place} font ${q(t.font)} size ${n(t.size)} align ${t.align} line ${n(t.lineHeight)} color ${t.color}`
  if (t.stroke) {
    s += ` stroke ${printPaint(t.stroke.paint)} ${n(t.stroke.width)}`
    if (t.stroke.cap) s += ` cap ${t.stroke.cap}`
    if (t.stroke.join) s += ` join ${t.stroke.join}`
    if (t.stroke.miterLimit != null) s += ` miter ${n(t.stroke.miterLimit)}`
    if (t.stroke.dash?.length) s += ` dash ${t.stroke.dash.map(n).join(',')}`
  }
  if (t.weight && t.weight >= 700) s += ' bold'
  if (t.italic) s += ' italic'
  // `box`/`wrap` are ignored for a path-laid run → not printed (keeps the round-trip clean).
  if (!tp) { s += ` box ${n(t.box.w)} ${n(t.box.h)}`; if (t.wrap) s += ' wrap' }
  if (t.bind) s += ` bind ${q(t.bind)}`
  if (t.decimals != null) s += ` decimals ${n(t.decimals)}`
  return s + printPoseAttrs(t, withExpr)
}

function printImage(im: Image, withExpr: boolean): string {
  // The NAME of the item (!= assetId) must round-trip: it acts as the key for cel poses (roster by name).
  const asName = im.name && im.name !== 'Image' ? ` as ${q(im.name)}` : ''
  return `image ${q(im.assetId)} ${n(im.w)} ${n(im.h)}${asName}${printTransform(im.transform)}` + printPoseAttrs(im, withExpr)
}

/** Playback keyword for the non-default modes: `loop` (independent) / `once`. `synced`/`singleFrame` → ''. */
function printPlayback(pb: InstancePlayback | undefined): string {
  if (pb?.mode === 'independent') return ' loop'
  if (pb?.mode === 'once') return ' once'
  return ''
}
function printInstance(it: Instance, ctx: Ctx): string {
  const sym = ctx.symName(it.symbolId)
  const asName = it.name !== sym ? ` as ${q(it.name)}` : ''
  return `instance ${q(sym)}${asName}${printTransform(it.transform)}` + printPoseAttrs(it, ctx.inlineExpr) + printPlayback(it.playback) + printCallSiteParams(it.params)
}
/** Call-site param values: ` { name = value, … }` (empty/absent → nothing). */
function printCallSiteParams(params?: Record<string, string>): string {
  const entries = params ? Object.entries(params) : []
  return entries.length ? ` { ${entries.map(([k, v]) => `${k} = ${v}`).join(', ')} }` : ''
}

function printItem(it: Item, depth: number, ctx: Ctx): string | null {
  const ind = IND.repeat(depth)
  if (isGroup(it)) return printGroup(it, depth, ctx)
  if (isInstance(it)) return ind + printInstance(it, ctx)
  if (isText(it)) return ind + printText(it, ctx.inlineExpr)
  if (isImage(it)) return ind + printImage(it, ctx.inlineExpr)
  return ind + printRegion(it, pathToData(it.path))
}

// ── Animation: easing · pose · substance · keyframe (cel) · timeline. ─────────
// NB: a Region's `as "<id>"` name is a SEPARATE namespace (resolved by text-on-path's own walk, cf.
// resolveTextPaths) — deliberately NOT surfaced here, so named shapes don't shadow same-named behavior
// objects (groups/text) in itemsByName / object-block / `@name` pose resolution.
const itemName = (it: Item): string => (isGroup(it) || isInstance(it) || isText(it) || isImage(it) ? it.name : '')
const printEasing = (e: Easing): string => (typeof e === 'string' ? e : `cubic(${e.cubic.map(n).join(',')})`)

function printPose(p: Pose, depth: number, rosterName: (id: string) => string): string {
  let s = `${IND.repeat(depth)}pose ${q(rosterName(p.id))}`
  if (p.transform) s += printTransform(p.transform) || ' at 0,0'
  if (p.rotate != null) s += ` rotate ${n(p.rotate)}`
  if (p.scaleX != null && p.scaleX === p.scaleY) s += ` scale ${n(p.scaleX)}`
  else { if (p.scaleX != null) s += ` scaleX ${n(p.scaleX)}`; if (p.scaleY != null) s += ` scaleY ${n(p.scaleY)}` }
  if (p.opacity != null) s += ` opacity ${n(p.opacity)}`
  if (p.tint) s += ` tint ${p.tint.param ?? p.tint.color} ${n(p.tint.amount)}`
  if (p.spin) s += ` spin ${p.spin}`
  if (p.turns) s += ` turns ${n(p.turns)}`
  if (p.filters) for (const f of p.filters) s += ' ' + printFilter(f)
  return s
}
function printMatter(regions: Region[], depth: number): string {
  const ind = IND.repeat(depth)
  const lines = regions.map((r) => IND.repeat(depth + 1) + printRegion(r, pathToData(r.path)))
  return `${ind}matter {\n${lines.join('\n')}\n${ind}}`
}
function printCel(c: Cel, depth: number, rosterName: (id: string) => string): string {
  let head = `cel ${n(c.frame)}`
  if (c.tween) head += ' tween'
  if (c.shapeTween) head += ' morph'
  if (c.ease) head += ` ease ${printEasing(c.ease)}`
  const lines = c.poses.map((p) => printPose(p, depth + 1, rosterName))
  if (c.matter && c.matter.length) lines.push(printMatter(c.matter, depth + 1))
  return `${IND.repeat(depth)}${head} {\n${lines.join('\n')}\n${IND.repeat(depth)}}`
}
const printTimeline = (tl: Timeline, depth: number) => `${IND.repeat(depth)}timeline ${n(tl.fps)} ${n(tl.durationFrames)}`

// Layers of a scope: the `parent` relationship (mask/guide/folder → children) is rendered by
// NESTING. We emit the roots (with no parent); each layer nests its children.
function printLayers(layers: Layer[], depth: number, ctx: Ctx): string {
  const childrenOf = new Map<string, Layer[]>()
  const top: Layer[] = []
  for (const l of layers) {
    if (l.parent) { const a = childrenOf.get(l.parent); if (a) a.push(l); else childrenOf.set(l.parent, [l]) }
    else top.push(l)
  }
  return top.map((l) => printLayer(l, depth, ctx, childrenOf)).join('\n')
}

function printLayer(l: Layer, depth: number, ctx: Ctx, childrenOf?: Map<string, Layer[]>): string {
  const ind = IND.repeat(depth)
  const rosterName = (id: string) => { const it = l.items.find((x) => x.id === id); return it ? itemName(it) : id }
  const lines = l.items.map((it) => printItem(it, depth + 1, ctx)).filter((x): x is string => x != null)
  if (l.cels?.length) for (const c of l.cels) lines.push(printCel(c, depth + 1, rosterName))
  for (const k of childrenOf?.get(l.id) ?? []) lines.push(printLayer(k, depth + 1, ctx, childrenOf)) // nested children
  const prefix = l.isMask ? 'mask ' : l.isGuide ? 'guide ' : l.isFolder ? 'folder ' : ''
  const mods = [
    l.orientToGuide ? 'orient' : '', l.maskOff ? 'off' : '', l.collapsed ? 'collapsed' : '',
    l.locked ? 'locked' : '', l.visible === false ? 'hidden' : '',
    l.opacity != null && l.opacity < 1 ? `opacity ${n(l.opacity)}` : '',
  ].filter(Boolean).join(' ')
  return `${ind}${prefix}layer ${q(l.name)}${mods ? ' ' + mods : ''} {\n${lines.join('\n')}${lines.length ? '\n' : ''}${ind}}`
}

function printGroup(g: Group, depth: number, ctx: Ctx): string {
  const ind = IND.repeat(depth)
  const head = g.timeline ? printTimeline(g.timeline, depth + 1) + '\n' : ''
  const layers = printLayers(g.layers, depth + 1, ctx)
  return `${ind}group ${q(g.name)}${printTransform(g.transform)}${printPoseAttrs(g, ctx.inlineExpr)} {\n${head}${layers}\n${ind}}`
}

function printSymbol(sym: SymbolDef, ctx: Ctx): string {
  const path = sym.folderId && ctx.folderPath ? ctx.folderPath(sym.folderId) : ''
  const inClause = path ? ` in ${q(path)}` : '' // library folder (organization)
  const head = sym.timeline ? printTimeline(sym.timeline, 1) + '\n' : ''
  const params = sym.params?.length ? printParams(sym.params, 1) + '\n' : ''
  const states = sym.states?.length ? sym.states.map((sm) => printStateMachine(sm, 1)).join('\n') + '\n' : ''
  const layers = printLayers(sym.layers, 1, ctx)
  return `symbol ${q(sym.name)}${inClause} {\n${head}${params}${states}${layers}\n}`
}

/** `params { <type> <name> = <default> [range <min> <max>] ["doc"] … }` */
function printParams(params: ParamDef[], depth: number): string {
  const ind = IND.repeat(depth)
  const lines = params.map((p) => {
    let s = `${IND.repeat(depth + 1)}${p.type} ${p.name} = ${p.default}`
    if (p.min != null || p.max != null) s += ` range ${n(p.min ?? p.max ?? 0)} ${n(p.max ?? p.min ?? 0)}`
    if (p.doc) s += ` ${q(p.doc)}`
    return s
  })
  return `${ind}params {\n${lines.join('\n')}\n${ind}}`
}

/** `states <param> { <name> at <frame> … [initial <name>] [transition <n> [ease <e>]] }` */
function printStateMachine(sm: StateMachine, depth: number): string {
  const parts = sm.states.map((s) => `${s.name} at ${n(s.frame)}`)
  if (sm.initial) parts.push(`initial ${sm.initial}`)
  if (sm.transition != null) parts.push(`transition ${n(sm.transition)}${sm.ease ? ` ease ${printEasing(sm.ease)}` : ''}`)
  return `${IND.repeat(depth)}states ${sm.param} { ${parts.join('  ')} }`
}

/** Prints a `.flat` library (list of symbols). `folders` (optional) → folder paths (`in "A/B"`). */
export function printFlat(symbols: SymbolDef[], folders?: Folder[]): string {
  const ctx: Ctx = {
    symName: (id) => symbols.find((s) => s.id === id)?.name ?? id,
    inlineExpr: true,
    ...(folders && folders.length ? { folderPath: (id: string) => folderPath(folders, id) } : {}),
  }
  return symbols.map((s) => printSymbol(s, ctx)).join('\n\n') + (symbols.length ? '\n' : '')
}

// ── `.flatink` program: size + background + variables + media + composition + behavior. ──
//  Symbols live ELSEWHERE (`.flat`); the program references them by NAME. Media
//  (image/sound) are declared by path (`asset`) and embedded at compile time.
export type Program = Pick<Doc, 'width' | 'height' | 'background' | 'layers' | 'variables' | 'symbols' | 'assets' | 'timeline' | 'interactions' | 'interactors' | 'imports' | 'functions'>

/** Prints the COMPOSITION part (size/background/variables/media/scene) of a program. */
export function printProgram(doc: Program): string {
  // Symbol ref by name: real id via doc.symbols, or `@Name` ref (already-parsed program).
  const symName = (id: string) => (id.startsWith('@') ? id.slice(1) : (doc.symbols.find((s) => s.id === id)?.name ?? id))
  const ctx: Ctx = { symName, inlineExpr: false } // expressions = behavior (object block), not the composition
  let out = `size ${n(doc.width)} ${n(doc.height)}\n`
  if (doc.background && doc.background.toLowerCase() !== '#ffffff') out += `background ${doc.background}\n`
  // Root timeline directive, only if it deviates from the implicit one (24 fps / 60 frames).
  const tl = doc.timeline
  if (tl && (tl.fps !== 24 || tl.durationFrames !== 60)) out += `timeline ${n(tl.fps)} ${n(tl.durationFrames)}\n`
  for (const name of doc.imports ?? []) out += `use ${q(name)}\n`
  for (const a of doc.assets ?? []) out += `asset ${q(a.id)} ${q(a.name)} ${a.kind}${a.family ? ` ${q(a.family)}` : ''}\n`
  for (const [name, val] of Object.entries(doc.variables ?? {})) out += `var ${name} = ${printVarValue(val)}\n`
  for (const s of doc.timeline?.sounds ?? []) out += `sound ${q(s.assetId)} at ${n(s.startFrame)}${s.gain != null && s.gain !== 1 ? ` gain ${n(s.gain)}` : ''}${s.loop ? ' loop' : ''}\n`
  out += `\nscene {\n${printLayers(doc.layers, 1, ctx)}\n}\n`
  return out
}

/** Parses the COMPOSITION of a `.flatink` program (`@Name` refs, resolved at compile time). */
export function parseProgram(src: string): Program {
  const parser = new FlatParser(tokenize(expandSceneRepeats(src)))
  const prog = parser.program()
  resolveAligns(prog, parser.pendingAligns) // `align …` anchors: bbox computable once the scene is built
  resolveTextPaths(prog, parser.pendingTextPaths) // `along "<id>"`: bake the shape outline into textPath
  return prog
}

// ── SCENE `repeat` / `def`: syntactic sugar unfolded at parse ──────────────────
//  • `repeat <i> from <a> to <b> { …items… }` (inside `scene { }`) → generates N items.
//  • `def <name> = <expr>` (wherever it is) → compile-time constant, removed from the source.
//  The loop index AND the `def`s are used inside numbers via `$(expr)` interpolation
//  (e.g. `at $(colG + i*gap),80`). Nested loops OK. The `repeat`s of `object`/timeline scripts
//  (RUNTIME loops) are left intact.
const REPEAT_BUDGET = 5000 // anti-explosion guard (sum of the unfolded iterations of a program)

/** Evaluates a COMPILE-TIME arithmetic expression with the loop variables `env`. */
function evalConst(src: string, env: Record<string, number>): number {
  const c = compileExpr(src)
  return c.ok ? evalExpr(c.node, exprScope(env, 0, 0), Number.NaN) : Number.NaN
}
/** Replaces the `$(expr)` interpolations of a fragment with their value (loop variables `env`). */
function interpolate(text: string, env: Record<string, number>): string {
  let out = '', i = 0
  while (i < text.length) {
    if (text[i] === '$' && text[i + 1] === '(') {
      let j = i + 2, depth = 1
      for (; j < text.length && depth > 0; j++) { if (text[j] === '(') depth++; else if (text[j] === ')') { depth--; if (depth === 0) break } }
      const expr = text.slice(i + 2, j)
      const v = evalConst(expr, env)
      out += Number.isFinite(v) ? String(Math.round(v * 1e6) / 1e6) : `$(${expr})` // invalid → left as is (parse error downstream)
      i = j + 1
    } else out += text[i++]
  }
  return out
}
/** Recursively unfolds the `repeat … { … }` of a scene fragment (interpolates `$()` along the way). */
function expandRepeats(text: string, env: Record<string, number>, budget: { n: number }): string {
  const m = /\brepeat\s+([A-Za-z_]\w*)\s+from\s+([^{]*?)\s+to\s+([^{]*?)\s*\{/.exec(text)
  if (!m) return interpolate(text, env)
  const open = m.index + m[0].length - 1
  const close = matchBrace(text, open)
  if (close < 0) return interpolate(text, env) // unclosed brace → left to the parser (hard error)
  const body = text.slice(open + 1, close)
  const a = Math.round(evalConst(m[2], env)), b = Math.round(evalConst(m[3], env))
  let out = interpolate(text.slice(0, m.index), env)
  if (Number.isFinite(a) && Number.isFinite(b)) {
    // `\n` between iterations: keeps ONE item per line (otherwise stuck-together `instance`s break their bounding). Tokenizer is indifferent.
    for (let k = a; k <= b && budget.n < REPEAT_BUDGET; k++) { budget.n++; out += expandRepeats(body, { ...env, [m[1]]: k }, budget) + '\n' }
  }
  return out + expandRepeats(text.slice(close + 1), env, budget)
}
/** Extracts the `def <name> = <expr>` constants (compile-time) and REMOVES their lines from the source.
 *  A `def` may reference the previous `def`s. Trailing `//` comments in the value are ignored. */
function extractDefs(src: string): { src: string; defs: Record<string, number> } {
  if (!/\bdef\b/.test(src)) return { src, defs: {} }
  const defs: Record<string, number> = {}
  const re = /^\s*def\s+([A-Za-z_]\w*)\s*=\s*(.+?)\s*$/
  const kept: string[] = []
  for (const line of src.split('\n')) {
    const m = re.exec(line)
    if (m) { defs[m[1]] = evalConst(m[2].replace(/\/\/.*$/, '').trim(), defs); continue } // evaluated with the previous defs
    kept.push(line)
  }
  return { src: kept.join('\n'), defs }
}
// ── PARAMETERIZED symbols: `symbol "X"(p, q = default) { … }` + `instance "X"(args) …` ──────────────
//  Reusable VISUAL template, expanded at PARSE (substitutes `$(param)` in the body, params are
//  numbers AND text/color). Each instance → a concrete `group`. Zero runtime cost (lightweight player).
const SYMBOL_BUDGET = 5000 // anti-recursion guard (total number of unfolded parameterized instances)
type SymbolTemplate = { params: { name: string; def?: string }[]; body: string }

/** Index of the closing parenthesis matching `open` (respects strings). -1 if absent. */
function matchParen(text: string, open: number): number {
  let depth = 0
  for (let i = open; i < text.length; i++) {
    const c = text[i]
    if (c === '"') { i++; while (i < text.length && text[i] !== '"') { if (text[i] === '\\') i++; i++ } }
    else if (c === '(') depth++
    else if (c === ')') { depth--; if (depth === 0) return i }
  }
  return -1
}
/** Splits on the depth-0 commas (respects "…", (), []). */
function splitTopLevel(text: string): string[] {
  const out: string[] = []
  let depth = 0, cur = '', inStr = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inStr) { cur += c; if (c === '"' && text[i - 1] !== '\\') inStr = false; continue }
    if (c === '"') { inStr = true; cur += c; continue }
    if (c === '(' || c === '[') depth++
    else if (c === ')' || c === ']') depth--
    if (c === ',' && depth === 0) { out.push(cur); cur = ''; continue }
    cur += c
  }
  if (cur.trim()) out.push(cur)
  return out
}
/** Signature `p, q = 150, t = "#fff"` → list of parameters (with optional text default). */
function parseSignature(text: string): { name: string; def?: string }[] {
  return splitTopLevel(text)
    .map((part) => { const eq = part.indexOf('='); return eq < 0 ? { name: part.trim() } : { name: part.slice(0, eq).trim(), def: part.slice(eq + 1).trim() } })
    .filter((p) => p.name)
}
/** An argument/default → its substitution value: string (without quotes), color, or number. */
function argToBinding(text: string): { raw: string; num?: number } {
  const t = text.trim()
  if (t.startsWith('"')) return { raw: t.slice(1, t.endsWith('"') ? -1 : undefined).replace(/\\(.)/g, (_, c) => (c === 'n' ? '\n' : c)) }
  if (t.startsWith('#')) return { raw: t }
  const num = Number(t)
  return Number.isFinite(num) && t !== '' ? { raw: t, num } : { raw: t }
}
/** Removes the PARAMETERIZED symbol definitions (`symbol "X"(…) { … }`) and returns them as templates.
 *  NON-parameterized symbols (`.flat` libraries) are not touched (no parenthesis). */
function extractSymbolTemplates(src: string): { src: string; templates: Map<string, SymbolTemplate> } {
  const templates = new Map<string, SymbolTemplate>()
  if (!/\bsymbol\b/.test(src)) return { src, templates }
  const re = /\bsymbol\s+"((?:[^"\\]|\\.)*)"\s*\(/g
  let out = '', cursor = 0
  for (;;) {
    re.lastIndex = cursor
    const m = re.exec(src)
    if (!m) { out += src.slice(cursor); break }
    const parenOpen = m.index + m[0].length - 1
    const parenClose = matchParen(src, parenOpen)
    const braceOpen = parenClose >= 0 ? src.indexOf('{', parenClose) : -1
    const braceClose = braceOpen >= 0 ? matchBrace(src, braceOpen) : -1
    if (braceClose < 0) { out += src.slice(cursor); break }
    templates.set(m[1], { params: parseSignature(src.slice(parenOpen + 1, parenClose)), body: src.slice(braceOpen + 1, braceClose) })
    out += src.slice(cursor, m.index) // removes the template definition
    cursor = braceClose + 1
  }
  return { src: out, templates }
}
/** Substitutes `$(param)` in a template body: param name → raw value (text/color/number),
 *  otherwise an arithmetic expression with the numeric params (e.g. `$(w/2)`). */
function substituteSymbolBody(body: string, env: Map<string, { raw: string; num?: number }>): string {
  const numEnv: Record<string, number> = {}
  for (const [k, v] of env) if (v.num !== undefined) numEnv[k] = v.num
  let out = '', i = 0
  while (i < body.length) {
    if (body[i] === '$' && body[i + 1] === '(') {
      let j = i + 2, depth = 1
      for (; j < body.length && depth > 0; j++) { if (body[j] === '(') depth++; else if (body[j] === ')') { depth--; if (depth === 0) break } }
      const expr = body.slice(i + 2, j)
      const param = env.get(expr.trim())
      if (param) out += param.raw
      else { const v = evalConst(expr, numEnv); out += Number.isFinite(v) ? String(Math.round(v * 1e6) / 1e6) : `$(${expr})` }
      i = j + 1
    } else out += body[i++]
  }
  return out
}
/** Builds the concrete `group` for an `instance "Tmpl"(args) [as "Name"] [transform/attrs]` call.
 *  Also returns the NAME of the group (for the template→groups registry, consumed by `each`). */
function buildSymbolGroup(tmpl: SymbolTemplate, name: string, argsText: string, trailing: string): { text: string; groupName: string } {
  const args = splitTopLevel(argsText).map((a) => a.trim()).filter((a) => a.length)
  if (args.length > tmpl.params.length) throw new Error(`instance "${name}": ${args.length} arguments for ${tmpl.params.length} parameter(s)`)
  const env = new Map<string, { raw: string; num?: number }>()
  for (let i = 0; i < tmpl.params.length; i++) {
    const a = args[i] ?? tmpl.params[i].def
    if (a === undefined) throw new Error(`instance "${name}": parameter "${tmpl.params[i].name}" missing (no argument and no default)`)
    env.set(tmpl.params[i].name, argToBinding(a))
  }
  const asM = /^\s*as\s+"((?:[^"\\]|\\.)*)"/.exec(trailing)
  const groupName = asM ? asM[1] : name
  const rest = asM ? trailing.slice(asM[0].length) : trailing // transform/attrs (` at x,y`, ` align …`, ` opacity …`)
  return { text: `group ${JSON.stringify(groupName)}${rest} {${substituteSymbolBody(tmpl.body, env)}}`, groupName }
}
/** Unfolds the `instance "Tmpl"(args) …` calls of a scene into concrete `group`s (successive passes
 *  for nested templates; anti-recursion budget). An `instance "X"(…)` without a template = error.
 *  `registry` (optional) receives, per template, the names of the generated groups IN ORDER (for `each`). */
function expandSymbolInstances(scene: string, templates: Map<string, SymbolTemplate>, registry?: Map<string, string[]>): string {
  let text = scene, budget = 0
  for (;;) {
    const re = /\binstance\s+"((?:[^"\\]|\\.)*)"\s*\(/g
    let out = '', cursor = 0, expanded = false
    for (;;) {
      re.lastIndex = cursor
      const m = re.exec(text)
      if (!m) { out += text.slice(cursor); break }
      const tmpl = templates.get(m[1])
      if (!tmpl) throw new Error(`parameterized instance: symbol "${m[1]}" not defined (a "symbol "${m[1]}"(…)" is expected)`)
      const parenClose = matchParen(text, m.index + m[0].length - 1)
      if (parenClose < 0) { out += text.slice(cursor); break }
      // The instance's trailing attrs (`as`/`at`/`align`/`opacity`/a call-site `{ … }` block) end at the
      // newline OR at the first `}` that closes an ENCLOSING block (depth 0) — so an instance can share a
      // line with the braces that close its layer/scene (`… at 50,50 } }`) without swallowing them.
      let end = parenClose + 1, depth = 0
      while (end < text.length) {
        const c = text[end]
        if (c === '\n') break
        if (c === '{') depth++
        else if (c === '}') { if (depth === 0) break; depth-- }
        end++
      }
      const built = buildSymbolGroup(tmpl, m[1], text.slice(m.index + m[0].length, parenClose), text.slice(parenClose + 1, end))
      if (registry) { const arr = registry.get(m[1]) ?? []; arr.push(built.groupName); registry.set(m[1], arr) }
      out += text.slice(cursor, m.index) + built.text
      cursor = end
      expanded = true
      if (++budget > SYMBOL_BUDGET) throw new Error('symbol expansion: too many instances (recursion?)')
    }
    text = out
    if (!expanded) break
  }
  return text
}
/** Extends `each "Tmpl" as i { … }` TO THE HANDLERS: if `Tmpl` is a parameterized template, unfolds into one
 *  `object "<group>" { … }` block per generated instance (index `i` substituted). The `each` on a REAL symbol
 *  (real instances) is left intact → runtime channel binding (Timeline.binds). */
function expandEachHandlers(src: string, registry: Map<string, string[]>, defs: Record<string, number> = {}): string {
  if (!registry.size || !/\beach\b/.test(src)) return src
  const re = /\beach\s+"((?:[^"\\]|\\.)*)"\s+as\s+([A-Za-z_]\w*)\s*\{/g
  let out = '', cursor = 0
  for (;;) {
    re.lastIndex = cursor
    const m = re.exec(src)
    if (!m) { out += src.slice(cursor); break }
    const names = registry.get(m[1])
    const braceOpen = m.index + m[0].length - 1
    const braceClose = matchBrace(src, braceOpen)
    if (!names || braceClose < 0) { out += src.slice(cursor, re.lastIndex); cursor = re.lastIndex; continue } // not a template → runtime each
    const body = src.slice(braceOpen + 1, braceClose)
    const sub = new RegExp(`\\b${m[2]}\\b`, 'g') // loop index → value (text substitution, like the binds)
    out += src.slice(cursor, m.index)
    // Per instance: first resolve `$(…)` that mixes `def`s and the loop index (e.g. `$(col + i*gap)`) — these
    // stayed intact through the global def pass because the index was unknown — THEN substitute the bare index.
    names.forEach((nm, k) => { out += `object ${JSON.stringify(nm)} {${interpolate(body, { ...defs, [m[2]]: k }).replace(sub, String(k))}}\n` })
    cursor = braceClose + 1
  }
  return out
}
/** Pre-expansion of the PROGRAM: removes `def` + symbol templates, resolves `$(def)` EVERYWHERE (scene AND
 *  object/each behavior), unfolds `repeat` (+ `$(index)`) in the scene, then unfolds the
 *  `instance "Tmpl"(…)` into groups. The `$()` not resolvable by `def`s alone (loop indices,
 *  symbol params) stay intact for their dedicated passes. */
export function expandSceneSugar(src: string): { src: string; symbolGroups: Map<string, string[]>; defs: Record<string, number> } {
  const symbolGroups = new Map<string, string[]>()
  const { src: s1, defs } = extractDefs(src)
  // $(def) resolved on the WHOLE source (object/each expressions benefit from it); $(loopvar)/$(param)
  // are NaN here → left as is for expandRepeats / expandEachHandlers / substituteSymbolBody. Cf. EDU feedback #3.
  const sd = Object.keys(defs).length ? interpolate(s1, defs) : s1
  const { src: s2, templates } = extractSymbolTemplates(sd)
  const hasParamInstance = /\binstance\s+"(?:[^"\\]|\\.)*"\s*\(/.test(s2) // parameterized call → always expand (otherwise hard error)
  if (!/\brepeat\b/.test(s2) && !/\$\(/.test(s2) && templates.size === 0 && !hasParamInstance) return { src: s2, symbolGroups, defs }
  const si = s2.search(/\bscene\b/)
  const open = si >= 0 ? s2.indexOf('{', si) : -1
  const close = open >= 0 ? matchBrace(s2, open) : -1
  if (close < 0) return { src: s2, symbolGroups, defs }
  let inner = expandRepeats(s2.slice(open + 1, close), defs, { n: 0 }) // repeat + $(index) → concrete instances
  inner = expandSymbolInstances(inner, templates, symbolGroups) // parameterized instances → groups (registry for `each`)
  return { src: s2.slice(0, open + 1) + inner + s2.slice(close), symbolGroups, defs }
}
/** Scene pre-expansion (facade returning just the text) — used by `parseProgram`. */
export function expandSceneRepeats(src: string): string {
  return expandSceneSugar(src).src
}

// ── `align <point> of "Name" [offset dx,dy]`: POSITION anchoring (resolved post-parse) ─────────────
/** WORLD coordinates of one of the 9 named points of the bbox. An axis not pinned by an edge = centered. */
function anchorPoint(b: BBox, point: string): { x: number; y: number } {
  const cx = (b.minX + b.maxX) / 2, cy = (b.minY + b.maxY) / 2
  const x = point.includes('left') ? b.minX : point.includes('right') ? b.maxX : cx
  const y = point.includes('top') ? b.minY : point.includes('bottom') ? b.maxY : cy
  return { x, y }
}
/** Resolves the `align`s: mutates each shared `tf` in place = point of the STATIC bbox of the target +
 *  offset. Several passes to handle chains (A aligned on B which is itself aligned); target not found
 *  = hard error. The bbox is static (scene transforms, without expression channels — like the drop
 *  zones). Positions in the scene root space (place source and target at the same level). */
function resolveAligns(prog: Program, aligns: PendingAlign[]): void {
  if (!aligns.length) return
  const doc = prog as unknown as Doc // Program has layers/symbols/width/height → enough for itemBoundsByName
  const pendingByName = new Map<string, number>() // aligned item → its index (to resolve the targets first)
  aligns.forEach((a, i) => { if (a.name) pendingByName.set(a.name, i) })
  const done = new Set<number>()
  for (let pass = 0; pass <= aligns.length && done.size < aligns.length; pass++) {
    for (let i = 0; i < aligns.length; i++) {
      if (done.has(i)) continue
      const a = aligns[i]
      const dep = pendingByName.get(a.target) // target itself aligned and not yet resolved → we wait
      if (dep !== undefined && dep !== i && !done.has(dep)) continue
      const b = itemBoundsByName(doc, a.target)
      if (!b) continue
      const pt = anchorPoint(b, a.point)
      a.tf.e = pt.x + a.dx
      a.tf.f = pt.y + a.dy
      done.add(i)
    }
  }
  const missing = [...new Set(aligns.filter((_, i) => !done.has(i)).map((a) => a.target))]
  if (missing.length) throw new Error(`align: item(s) not found: ${missing.join(', ')}`)
}

/** Resolves `text … along "<ref>"`: bakes the named shape's outline into `text.textPath.path` (closed
 *  sources are top-anchored, cf. normalizeClosedForText). Throws if a `ref` names no shape. */
function resolveTextPaths(prog: Program, pending: PendingTextPath[]): void {
  if (!pending.length) return
  const shapes = new Map<string, Path>() // shape name → outline (regions only — text follows a drawn shape)
  const walk = (ls: Layer[]) => {
    for (const l of ls) for (const it of l.items) {
      if (isGroup(it)) walk(it.layers)
      else if (!isText(it) && !isImage(it) && !isInstance(it)) { const r = it as Region; if (r.name && !shapes.has(r.name)) shapes.set(r.name, r.path) }
    }
  }
  walk(prog.layers)
  const missing: string[] = []
  for (const p of pending) {
    const src = shapes.get(p.ref)
    if (!src) { missing.push(p.ref); continue }
    p.text.textPath = { ref: p.ref, path: normalizeClosedForText(src), ...(p.start ? { start: p.start } : {}), ...(p.side ? { side: p.side } : {}), ...(p.spacing ? { spacing: p.spacing } : {}), ...(p.startExpr ? { startExpr: p.startExpr } : {}), ...(p.spacingExpr ? { spacingExpr: p.spacingExpr } : {}) }
  }
  if (missing.length) throw new Error(`along: shape not found: ${[...new Set(missing)].join(', ')}`)
}

// ── `match`: declarative matching sugar (unfolded into `object` blocks) ───────
//  `match <Items> onto <Zones> { correct <I> -> <Z>, … [lock on wrong] [on correct/wrong as it {…}] [on done {…}] }`
//  Generates, per item: `drag <I>_x, <I>_y { enabled <I>_placed == 0 }` + one `dropped on` per zone that sets
//  the state (`<I>_placed`/`<I>_ok`/`<I>_zone`) then runs the hook actions (generic — no event imposed,
//  cf. Moiki decoupling). Default is RETRYABLE (a wrong zone does not lock); `lock on wrong` = strict.
//  Completion: each correct drop tests "all _ok == 1" → runs `on done` (no counter/init).
const subBinder = (text: string, binder: string, item: string): string =>
  text.replace(new RegExp(`text\\(\\s*${binder}\\s*\\)`, 'g'), `text("${item}")`).replace(new RegExp(`\\b${binder}\\b`, 'g'), item)
function extractAsHook(body: string, kind: string): { binder: string; body: string } | null {
  const m = new RegExp(`\\bon\\s+${kind}\\s+as\\s+([A-Za-z_]\\w*)\\s*\\{`).exec(body)
  if (!m) return null
  const open = m.index + m[0].length - 1, close = matchBrace(body, open)
  return close < 0 ? null : { binder: m[1], body: body.slice(open + 1, close) }
}
function extractDoneHook(body: string): string | null {
  const m = /\bon\s+done\s*\{/.exec(body)
  if (!m) return null
  const open = m.index + m[0].length - 1, close = matchBrace(body, open)
  return close < 0 ? null : body.slice(open + 1, close)
}
function generateMatch(items: string[], zones: string[], body: string): string {
  const correctOf: Record<string, string> = {}
  const cm = /\bcorrect\s+([^\n]+)/.exec(body)
  if (cm) for (const pair of cm[1].split(',')) { const mm = /(.+?)->(.+)/.exec(pair); if (mm) correctOf[mm[1].trim()] = mm[2].trim() }
  const lock = /\block\s+on\s+wrong\b/.test(body)
  const hookOk = extractAsHook(body, 'correct'), hookKo = extractAsHook(body, 'wrong'), hookDone = extractDoneHook(body)
  const allOk = items.map((it) => `${it}_ok == 1`).join(' && ')
  const pushHook = (lines: string[], h: { binder: string; body: string } | null, it: string, ind: string) => {
    if (h) for (const l of subBinder(h.body, h.binder, it).split('\n')) if (l.trim()) lines.push(ind + l.trim())
  }
  let out = ''
  for (const it of items) {
    const zc = correctOf[it]
    if (!zc) continue // item with no declared correct zone → ignored (the lint will flag the missing zone)
    // `!= 1` (and not `== 0`): robust when the var is not yet initialized (undefined != 1 = true → drag active).
    const L: string[] = [`object "${it}" {`, `  drag ${it}_x, ${it}_y { enabled ${it}_placed != 1 }`]
    L.push(`  when dropped on ${zc} at pointer {`, `    ${it}_placed = 1`, `    ${it}_ok = 1`, `    ${it}_zone = ${zones.indexOf(zc) + 1}`)
    pushHook(L, hookOk, it, '    ')
    if (hookDone) { L.push(`    if (${allOk}) {`); for (const l of hookDone.split('\n')) if (l.trim()) L.push(`      ${l.trim()}`); L.push('    }') }
    L.push('  }')
    for (const z of zones) {
      if (z === zc) continue
      L.push(`  when dropped on ${z} at pointer {`, `    ${it}_ok = 0`, `    ${it}_zone = ${zones.indexOf(z) + 1}`)
      if (lock) L.push(`    ${it}_placed = 1`)
      pushHook(L, hookKo, it, '    ')
      L.push('  }')
    }
    L.push('}')
    out += L.join('\n') + '\n\n'
  }
  return out
}
/** Unfolds the `match … onto … { … }` blocks into `object` blocks (declarative matching sugar). No-op if absent. */
// ── `feedback <tokens>`: 1-line reactive feedback (unfolds into channel bindings) ───────────────────
//  Inside an `object` block: `feedback lift tilt dim shake(<expr>)` → channel bindings that call the
//  `feedback` stdlib, driven by self.hovered/self.grabbed. Composes PER CHANNEL (scaleX/scaleY/opacity/
//  rotation) so it never clashes with the object's x/y position bindings. Tokens:
//    lift  → hover grow (scaleX, and scaleY factor)   tilt → grab squash (scaleY factor)
//    dim   → hover opacity                            shake(<expr>) → refusal wobble (rotation), <expr> ≠ 0
/** Expand the `feedback …` sugar into channel bindings + ensure `use "feedback"`. */
export function expandFeedback(src: string): string {
  if (!/\bfeedback\b/.test(src)) return src
  let used = false
  const out = src.replace(/^([ \t]*)feedback\b([^\n]*)$/gm, (full: string, indent: string, rest: string) => {
    const tokens: { t: string; arg?: string }[] = []
    const re = /shake\(\s*([^)]*?)\s*\)|([A-Za-z][\w-]*)/g
    let m: RegExpExecArray | null
    while ((m = re.exec(rest))) tokens.push(m[1] !== undefined ? { t: 'shake', arg: m[1] } : { t: m[2] })
    const has = (t: string) => tokens.some((x) => x.t === t)
    const lines: string[] = []
    if (has('lift')) lines.push('scaleX = lift(self.hovered)')
    if (has('lift') || has('tilt')) {
      const f: string[] = []
      if (has('lift')) f.push('lift(self.hovered)')
      if (has('tilt')) f.push('tilt(self.grabbed)')
      lines.push('scaleY = ' + f.join(' * '))
    }
    if (has('dim')) lines.push('opacity = dim(self.hovered)')
    const shake = tokens.find((x) => x.t === 'shake')
    if (shake) lines.push(`rotation = shake(${shake.arg && shake.arg.length ? shake.arg : '0'}, time)`)
    if (!lines.length) return full // nothing recognized → leave as-is
    used = true
    return lines.map((l) => indent + l).join('\n')
  })
  if (!used || /(^|\n)\s*use\s+"feedback"/.test(out)) return out
  // Inject the import AFTER the `size` line (size must stay the first directive).
  const sz = /^[ \t]*size\b[^\n]*\n/m.exec(out)
  if (sz) { const i = sz.index + sz[0].length; return out.slice(0, i) + 'use "feedback"\n' + out.slice(i) }
  return `use "feedback"\n${out}`
}

export function expandMatch(src: string): string {
  if (!/\bmatch\b/.test(src)) return src
  const re = /\bmatch\s+([^{]+?)\s+onto\s+([^{]+?)\s*\{/g
  let out = '', cursor = 0
  for (;;) {
    re.lastIndex = cursor
    const m = re.exec(src)
    if (!m) { out += src.slice(cursor); break }
    const open = m.index + m[0].length - 1, close = matchBrace(src, open)
    if (close < 0) { out += src.slice(cursor); break }
    out += src.slice(cursor, m.index)
    const items = m[1].split(',').map((s) => s.trim()).filter(Boolean)
    const zones = m[2].split(',').map((s) => s.trim()).filter(Boolean)
    out += generateMatch(items, zones, src.slice(open + 1, close))
    cursor = close + 1
  }
  return out
}

const itemsByName = (layers: Layer[]): Map<string, Item> => {
  const m = new Map<string, Item>()
  // A text leaf's NAME is its content; its `as "<id>"` lives in a SEPARATE namespace (consumed by
  // `text("<id>")`). Index that id too so `object "<id>" { … }` can address (gate/animate) a bare text
  // leaf — otherwise the `object` block silently no-ops (it resolves targets by name, never by text id).
  const walk = (ls: Layer[]) => { for (const l of ls) for (const it of l.items) { const nm = itemName(it); if (nm && !m.has(nm)) m.set(nm, it); if (isText(it) && it.idExplicit && !m.has(it.id)) m.set(it.id, it); if (isGroup(it)) walk(it.layers) } }
  walk(layers)
  return m
}
const namedInfo = (layers: Layer[]): { id: string; name: string; expr?: Partial<Record<ExprChannel, string>> }[] => {
  const out: { id: string; name: string; expr?: Partial<Record<ExprChannel, string>> }[] = []
  const walk = (ls: Layer[]) => { for (const l of ls) for (const it of l.items) { const nm = itemName(it); if (nm) out.push({ id: it.id, name: nm, expr: isPoseable(it) ? it.expressions : undefined }); if (isGroup(it)) walk(it.layers) } }
  walk(layers)
  return out
}
const indentBlock = (s: string) => s.split('\n').map((l) => (l ? IND + l : l)).join('\n')

/** Index of the closing brace matching the one at `open` (respects strings and comments). */
function matchBrace(text: string, open: number): number {
  let depth = 0, i = open
  while (i < text.length) {
    const c = text[i]
    if (c === '"') { i++; while (i < text.length && text[i] !== '"') { if (text[i] === '\\') i++; i++ } }
    else if (c === '/' && text[i + 1] === '/') { while (i < text.length && text[i] !== '\n') i++ }
    else if (c === '{') depth++
    else if (c === '}') { depth--; if (depth === 0) return i }
    i++
  }
  return -1
}

/** Prints the FULL PROGRAM: composition + scene scripts + object blocks. */
export function printProgramFull(doc: Program): string {
  let out = printProgram(doc)
  if (doc.functions?.length) out += '\n' + printUnits(functionsToUnits(doc.functions))
  const sceneUnits = timelineToUnits(doc.timeline)
  if (sceneUnits.length) out += '\n' + printUnits(sceneUnits)
  for (const o of namedInfo(doc.layers)) {
    const units = objectToUnits(o.id, doc.interactions, o.expr, doc.interactors)
    if (units.length) out += `\nobject ${q(o.name)} {\n${indentBlock(printUnits(units))}}\n`
  }
  return out
}

/** The editor as a GENERATOR: a Doc → `.flat` source files (assets) + `.flatink` (program)
 *  + the media (to be written alongside; the program references them by path). Pure. */
export function exportFlatProject(doc: Doc): { flat: string; flatink: string; media: { path: string; mime: string; data: string }[] } {
  return {
    flat: printFlat(doc.symbols, doc.folders),
    flatink: printProgramFull(doc),
    media: (doc.assets ?? []).map((a) => ({ path: a.name, mime: a.mime, data: a.data })),
  }
}

/** Unfolds ALL the authoring sugar (feedback/match/def·repeat·symbols/each) → the real DSL. Shared by
 *  `parseProgramFull` and `behaviorDiagnostics` so both see the exact same expanded source. */
function expandProgramSugar(src: string): string {
  src = expandFeedback(src) // `feedback …` sugar → channel bindings (+ `use "feedback"`)
  src = expandMatch(src) // `match … onto …` sugar → `object` blocks (before extracting the behavior)
  const { src: expanded, symbolGroups, defs } = expandSceneSugar(src) // def/repeat/parameterized symbols → groups (+ registry + defs)
  return expandEachHandlers(expanded, symbolGroups, defs) // `each "Tmpl" as i { … }` → `object` blocks per generated instance ($(def+index) resolved)
}

/** Blanks every non-newline char of a span (position-preserving mask): keeps line/column offsets intact
 *  so a slice that REMOVES a sub-region still maps 1:1 onto the source for diagnostics. */
const blankSpan = (s: string) => s.replace(/[^\n]/g, ' ')

/** Single-line composition directives (header). Masked out of the behavior source so they don't reach the
 *  DSL parser — everything else outside the `scene { … }` block IS behavior, wherever it sits. */
const HEADER_DIRECTIVE = /^[ \t]*(?:size|background|timeline|var|asset|sound|use)\b[^\n]*/gm

/** Splits an EXPANDED program into the scene-script text + the `object "name" { … }` blocks. Behavior is
 *  taken from the WHOLE program (before AND after the `scene { … }` block) — so a `fn` / `every frame` /
 *  `object` placed in the header is honored, not silently dropped — with the scene block and the header
 *  composition directives MASKED (blanked, newlines kept) so only behavior reaches the DSL parser and every
 *  offset stays 1:1 with the source. `bodyAt` = absolute offset of each object body (drives line mapping). */
function extractBehavior(expanded: string): { sceneText: string; tailAt: number; objects: { name: string; body: string; bodyAt: number }[] } {
  const si = expanded.search(/\bscene\b/)
  const open = si >= 0 ? expanded.indexOf('{', si) : -1
  const close = open >= 0 ? matchBrace(expanded, open) : -1
  // Mask the `scene { … }` block (from the `scene` KEYWORD through its `}`), then the header composition
  // directives (before it). What remains, anywhere in the program, is behavior.
  let src = close >= 0 ? expanded.slice(0, si) + blankSpan(expanded.slice(si, close + 1)) + expanded.slice(close + 1) : expanded
  const headerEnd = si >= 0 ? si : src.length
  src = src.slice(0, headerEnd).replace(HEADER_DIRECTIVE, blankSpan) + src.slice(headerEnd)

  // Extracts the `object "name" { … }` blocks; the rest (object spans blanked out) = scene scripts.
  let sceneText = '', i = 0
  const objects: { name: string; body: string; bodyAt: number }[] = []
  while (i < src.length) {
    const m = /object\s+"((?:[^"\\]|\\.)*)"\s*\{/.exec(src.slice(i))
    if (!m) { sceneText += src.slice(i); break }
    const start = i + m.index
    sceneText += src.slice(i, start)
    const ob = start + m[0].length - 1
    const oc = matchBrace(src, ob)
    if (oc < 0) { sceneText += src.slice(start); break }
    objects.push({ name: m[1].replace(/\\(.)/g, (_, c) => (c === 'n' ? '\n' : c)), body: src.slice(ob + 1, oc), bodyAt: ob + 1 })
    sceneText += blankSpan(src.slice(start, oc + 1)) // mask the object span (keep newlines) → scene stays aligned
    i = oc + 1
  }
  return { sceneText, tailAt: 0, objects } // sceneText is now absolute-positioned (whole program) → base line 1
}

/** Parse-level diagnostics of the BEHAVIOR (`object` block bodies AND scene scripts) — the unknown
 *  channels / malformed statements (e.g. an incomplete `x =` with no value) that `parseProgramFull`
 *  DROPS silently (it keeps only `.units`, discarding `.diagnostics`). The Doc-based linter can't recover
 *  them: a dropped binding/action never reaches the model. Without this, `--check` would wave through e.g.
 *  `object "X" { scaleZ = 1 }`. (Two statements on one line — `a = 1  b = 2` — is NOT an error: the parser
 *  splits at the boundary.) Errors only, scoped by `object "name"` / `scene`, with line numbers absolute
 *  in the (expanded) source. */
export function behaviorDiagnostics(src: string): { scope: string; diag: Diagnostic }[] {
  const expanded = expandProgramSugar(src)
  const lineAt = (off: number) => expanded.slice(0, off).split('\n').length // 1-based line at an absolute offset
  const out: { scope: string; diag: Diagnostic }[] = []
  const { sceneText, tailAt, objects } = extractBehavior(expanded)
  for (const ob of objects) {
    const base = lineAt(ob.bodyAt)
    for (const d of parseUnits(ob.body).diagnostics) out.push({ scope: `object "${ob.name}"`, diag: { ...d, line: d.line + base - 1 } })
  }
  const sceneBase = lineAt(tailAt) // scene scripts begin right after the `}` of the `scene { … }` block
  for (const d of parseUnits(sceneText).diagnostics) out.push({ scope: 'scene', diag: { ...d, line: d.line + sceneBase - 1 } })
  return out
}

/** Parses the FULL PROGRAM → partial doc (composition + timeline + interactions; refs by name). */
export function parseProgramFull(src: string): Program {
  src = expandProgramSugar(src)
  const composition = parseProgram(src) // re-unfolds (no-op: already expanded) then tokenize/parse
  const { sceneText, objects } = extractBehavior(src)

  const result: Program = { ...composition }
  const sceneUnits = parseUnits(sceneText).units
  const tlScripts = unitsToTimeline(sceneUnits)
  const baseTl = composition.timeline ?? { fps: 24, durationFrames: 60, tracks: [] }
  // Preserves the root timeline if there are scene scripts, sounds, OR a `timeline` directive (custom fps/dur).
  if (Object.keys(tlScripts).length || composition.timeline) result.timeline = { ...baseTl, ...tlScripts }
  const functions = unitsToFunctions(sceneUnits)
  if (functions.length) result.functions = functions

  const byName = itemsByName(composition.layers)
  const interactions: Interaction[] = []
  const interactors: Interactor[] = []
  for (const ob of objects) {
    const item = byName.get(ob.name)
    const targetId = item?.id ?? '@' + ob.name
    const { events, drops, interactor, expressions } = unitsToObject(parseUnits(ob.body).units)
    if (item && isPoseable(item) && Object.keys(expressions).length) item.expressions = expressions
    for (const ev of events) interactions.push({ id: uid('int'), targetId, event: ev.event, actions: ev.actions })
    for (const d of drops) interactions.push({ id: uid('int'), targetId, event: 'drop', over: d.over, ...(d.atPointer ? { atPointer: true } : {}), actions: d.actions })
    if (interactor) interactors.push({ targetId, ...interactor })
  }
  if (interactions.length) result.interactions = interactions
  if (interactors.length) result.interactors = interactors
  return result
}

// ── Parse (text → model) — tokenizer + recursive descent. ──────────────────────
type Tok = { k: 'id' | 'num' | 'str' | 'color' | 'punc'; v: string }

function tokenize(src: string): Tok[] {
  const out: Tok[] = []
  let i = 0
  const N = src.length
  while (i < N) {
    const c = src[i]
    if (c === ' ' || c === '\t' || c === '\n' || c === '\r') { i++; continue }
    if (c === '/' && src[i + 1] === '/') { while (i < N && src[i] !== '\n') i++; continue }
    if (c === '"') {
      let v = ''
      i++
      while (i < N && src[i] !== '"') { if (src[i] === '\\') { i++; v += src[i] === 'n' ? '\n' : src[i] } else v += src[i]; i++ }
      i++
      out.push({ k: 'str', v })
      continue
    }
    if (c === '#') { let j = i + 1; while (j < N && /[0-9a-fA-F]/.test(src[j])) j++; out.push({ k: 'color', v: src.slice(i, j) }); i = j; continue }
    if (c === '-' || c === '.' || (c >= '0' && c <= '9')) {
      let j = i + 1
      while (j < N && /[0-9.eE+-]/.test(src[j]) && !(src[j] === '-' && !/[eE]/.test(src[j - 1]))) j++
      out.push({ k: 'num', v: src.slice(i, j) })
      i = j
      continue
    }
    if (/[a-zA-Z_]/.test(c)) { let j = i + 1; while (j < N && /[\w-]/.test(src[j])) j++; out.push({ k: 'id', v: src.slice(i, j) }); i = j; continue }
    if ('{}(),:=[]@'.includes(c)) { out.push({ k: 'punc', v: c }); i++; continue } // `@` = alpha marker in a param gradient stop (`0:teinte@0.8`)
    i++
  }
  return out
}

type ParsedAttrs = { opacity?: number; pivot?: { x: number; y: number }; tint?: Tint; filters?: Filter[]; expressions?: Partial<Record<ExprChannel, string>>; noHit?: boolean; blend?: BlendMode; hitbox?: { w: number; h: number }; clip?: { x: number; y: number; w: number; h: number }; playback?: InstancePlayback }

/** An `align <point> of "target" [offset]` pending: `tf` is the SHARED ref with the item, mutated
 *  in place by resolveAligns once the scene is parsed (the bbox of `target` is then computable). */
type PendingAlign = { tf: Transform; point: string; target: string; dx: number; dy: number; name?: string }
// `text … along "<ref>"`: the shape outline is resolved + baked into `text.textPath` once the scene is parsed.
type PendingTextPath = { text: Text; ref: string; start?: number; side?: 'over' | 'under'; spacing?: number; startExpr?: string; spacingExpr?: string }
const ANCHOR_POINTS: ReadonlySet<string> = new Set(['center', 'top', 'bottom', 'left', 'right', 'topleft', 'topright', 'bottomleft', 'bottomright'])

/**
 * Compile-time `cel … hold {}` sugar: a `hold` cel CARRIES FORWARD the previous cel's poses for every
 * container it does not itself mention, so a static/unchanged container persists without re-typing it
 * each keyframe. Pure rewrite (left→right, so chained holds accumulate) → the runtime sees a normal,
 * complete cel; the default (omission removes a container) is unchanged. `spin`/`turns` (tween-direction
 * hints) are dropped on carry — a carried pose is a HOLD, not a re-stated motion. Strips the `hold` flag.
 */
function expandHoldCels(cels: Cel[]): void {
  for (let i = 0; i < cels.length; i++) {
    const c = cels[i] as Cel & { hold?: boolean }
    if (!c.hold) continue
    delete c.hold
    if (i === 0) continue // nothing to carry from
    const present = new Set(c.poses.map((p) => p.id))
    for (const p of cels[i - 1].poses) {
      if (present.has(p.id)) continue
      const { spin: _s, turns: _t, ...rest } = p // carry as a static HOLD (no inherited tween direction)
      c.poses.push({ ...rest })
    }
  }
}

class FlatParser {
  private p = 0
  private cw = 800 // canvas dimensions (updated when parsing `size`) → `at center` anchor
  private ch = 600
  private readonly aligns: PendingAlign[] = []
  get pendingAligns(): PendingAlign[] { return this.aligns }
  private readonly textPaths: PendingTextPath[] = []
  get pendingTextPaths(): PendingTextPath[] { return this.textPaths }
  // Color-param defaults of the symbol being parsed (name → default hex) — the fallback color for a stop/tint
  // bound to a param (`0:teinte@…`, `tint teinte …`), so it renders even outside an instance scope.
  private colorDefaults = new Map<string, string>()
  constructor(private readonly t: Tok[]) {}
  private peek() { return this.t[this.p] }
  private next() { return this.t[this.p++] }
  private is(v: string) { const k = this.t[this.p]; return !!k && k.v === v }
  private eat(v: string) { if (!this.is(v)) throw new Error(`"${v}" expected, "${this.peek()?.v ?? 'end'}" found`); this.p++ }
  private num() { return Number(this.next().v) }
  private str() { return this.next().v }
  /** Value of a program variable: number, `fill(n, v)`, or array literal `[a, b, …]`. */
  private varValue(): number | number[] {
    if (this.is('[')) {
      this.eat('[')
      const arr: number[] = []
      while (!this.is(']')) { arr.push(this.num()); if (this.is(',')) this.eat(',') }
      this.eat(']')
      return arr
    }
    if (this.is('fill')) {
      this.eat('fill'); this.eat('('); const len = this.num(); this.eat(','); const val = this.num(); this.eat(')')
      return Array<number>(Math.max(0, Math.floor(len))).fill(val)
    }
    return this.num()
  }

  // Library folders reconstructed from the `in "A/B"` clauses (deduplicated by parent+name).
  private folders: Folder[] = []
  get parsedFolders(): Folder[] { return this.folders }
  private folderIdForPath(path: string): string | undefined {
    const segs = path.split('/').map((s) => s.trim()).filter(Boolean)
    let parent: string | undefined
    for (const name of segs) {
      let f = this.folders.find((x) => x.name === name && x.parent === parent)
      if (!f) { f = { id: uid('fld'), name, ...(parent ? { parent } : {}) }; this.folders.push(f) }
      parent = f.id
    }
    return parent
  }

  parse(): SymbolDef[] {
    const out: SymbolDef[] = []
    while (this.peek() && this.is('symbol')) out.push(this.symbol())
    return out
  }
  // Program: size + background + variables + media (asset/sound) + scene composition.
  program(): Program {
    let width = 800, height = 600
    let background: string | undefined
    const variables: Record<string, number | number[]> = {}
    const imports: string[] = []
    const assets: Asset[] = []
    const sounds: SoundClip[] = []
    let stage: { fps: number; durationFrames: number } | undefined // root `timeline <fps> <dur>` directive
    if (this.is('size')) { this.next(); width = this.num(); height = this.num(); this.cw = width; this.ch = height }
    for (;;) {
      if (this.is('background')) { this.next(); background = this.next().v }
      else if (this.is('use')) { this.next(); imports.push(this.str()) }
      else if (this.is('var')) { this.next(); const name = this.next().v; this.eat('='); variables[name] = this.varValue() }
      else if (this.is('timeline')) { const tl = this.timeline(); stage = { fps: tl.fps, durationFrames: tl.durationFrames } }
      else if (this.is('asset')) {
        this.next(); const id = this.str(); const path = this.str(); const kind = this.next().v as Asset['kind']
        // Optional family alias for `font` assets: `asset "id" "f.woff2" font "Quicksand"`.
        const family = kind === 'font' && this.peek()?.k === 'str' ? this.str() : undefined
        assets.push({ id, name: path, kind, mime: '', data: path, ...(family ? { family } : {}) })
      }
      else if (this.is('sound')) {
        this.next(); const assetId = this.str(); this.eat('at'); const startFrame = this.num()
        let gain: number | undefined, loop = false
        for (;;) { if (this.is('gain')) { this.next(); gain = this.num() } else if (this.is('loop')) { this.next(); loop = true } else break }
        sounds.push({ id: uid('snd'), assetId, startFrame, ...(gain != null ? { gain } : {}), ...(loop ? { loop } : {}) })
      }
      // Behavior (fn / every frame / object / label) mistakenly placed BEFORE the scene block: skip its
      // tokens so we still reach (and parse) the `scene { … }` block — it is parsed separately as behavior
      // by `extractBehavior`. Without this, the composition parser bailed here and dropped the WHOLE scene.
      else if (this.peek() && !this.is('scene')) this.next()
      else break
    }
    const layers: Layer[] = []
    if (this.is('scene')) {
      this.next(); this.eat('{')
      while (!this.is('}')) layers.push(...this.layer())
      this.eat('}')
    }
    // Root timeline if a `timeline` directive or sounds are present (otherwise: static by default).
    const timeline: Timeline | undefined = stage || sounds.length
      ? { fps: stage?.fps ?? 24, durationFrames: stage?.durationFrames ?? 60, tracks: [], ...(sounds.length ? { sounds } : {}) }
      : undefined
    return { width, height, ...(background ? { background } : {}), layers, variables, symbols: [], ...(imports.length ? { imports } : {}), ...(assets.length ? { assets } : {}), ...(timeline ? { timeline } : {}) }
  }
  private symbol(): SymbolDef {
    this.eat('symbol')
    const name = this.str()
    const folderId = this.is('in') ? (this.next(), this.folderIdForPath(this.str())) : undefined // library folder
    this.eat('{')
    let timeline: Timeline | undefined
    const states: StateMachine[] = []
    const params: ParamDef[] = []
    for (;;) { // header blocks accepted in ANY order before the layers (timeline / params / states)
      if (this.is('timeline')) timeline = this.timeline()
      else if (this.is('states')) states.push(this.stateMachine())
      else if (this.is('params')) params.push(...this.paramsBlock())
      else break
    }
    // Expose this symbol's color-param defaults so a stop/tint bound to a param keeps a usable fallback hex.
    this.colorDefaults = new Map(params.filter((p) => p.type === 'color').map((p) => [p.name, p.default]))
    const layers: Layer[] = []
    while (!this.is('}')) layers.push(...this.layer())
    this.eat('}')
    this.colorDefaults = new Map()
    return { id: uid('sym'), name, layers, ...(timeline ? { timeline } : {}), ...(params.length ? { params } : {}), ...(states.length ? { states } : {}), ...(folderId ? { folderId } : {}) }
  }
  /** `params { <type> <name> = <default> [range <min> <max>] ["doc"] … }` — color | number | bool. */
  private paramsBlock(): ParamDef[] {
    this.eat('params'); this.eat('{')
    const out: ParamDef[] = []
    while (!this.is('}')) {
      const type = this.next().v
      if (type !== 'color' && type !== 'number' && type !== 'bool') throw new Error(`param type expected (color/number/bool): "${type}"`)
      const name = this.next().v
      this.eat('=')
      const def = this.next().v // raw default literal (#color / number / true|false)
      let min: number | undefined, max: number | undefined
      if (this.is('range')) { this.next(); min = this.num(); max = this.num() }
      const doc = this.peek()?.k === 'str' ? this.str() : undefined
      out.push({ name, type, default: def, ...(min != null ? { min } : {}), ...(max != null ? { max } : {}), ...(doc ? { doc } : {}) })
    }
    this.eat('}')
    return out
  }
  /** `states <param> { <name> at <frame> … [initial <name>] [transition <n> [ease <e>]] }` */
  private stateMachine(): StateMachine {
    this.eat('states')
    const param = this.next().v
    this.eat('{')
    const anchors: StateAnchor[] = []
    let initial: string | undefined, transition: number | undefined, ease: Easing | undefined
    // `initial`/`transition` are keywords UNLESS followed by `at` (then they're a state name — disambiguated
    // by lookahead, so a state may legitimately be named "initial"/"transition").
    while (!this.is('}')) {
      if (this.is('initial') && this.t[this.p + 1]?.v !== 'at') { this.next(); initial = this.next().v }
      else if (this.is('transition') && this.t[this.p + 1]?.v !== 'at') { this.next(); transition = this.num(); if (this.is('ease')) { this.next(); ease = this.easing() } }
      else { const name = this.next().v; this.eat('at'); const frame = this.num(); anchors.push({ name, frame }) }
    }
    this.eat('}')
    return { param, states: anchors, ...(initial ? { initial } : {}), ...(transition != null ? { transition } : {}), ...(ease ? { ease } : {}) }
  }
  // Returns the layer + its nested children FLATTENED (flat model: siblings + `parent`).
  private layer(parent?: string): Layer[] {
    let isMask = false, isGuide = false, isFolder = false
    if (this.is('mask')) { this.next(); isMask = true }
    else if (this.is('guide')) { this.next(); isGuide = true }
    else if (this.is('folder')) { this.next(); isFolder = true }
    this.eat('layer')
    const name = this.str()
    let opacity = 1, orientToGuide = false, maskOff = false, collapsed = false, locked = false, hidden = false
    for (;;) {
      if (this.is('opacity')) { this.next(); opacity = this.num() }
      else if (this.is('orient')) { this.next(); orientToGuide = true }
      else if (this.is('off')) { this.next(); maskOff = true }
      else if (this.is('collapsed')) { this.next(); collapsed = true }
      else if (this.is('locked')) { this.next(); locked = true }
      else if (this.is('hidden')) { this.next(); hidden = true }
      else break
    }
    this.eat('{')
    const id = uid('L')
    const items: Item[] = []
    while (this.is('path') || this.is('circle') || this.is('ellipse') || this.is('rect') || this.is('group') || this.is('instance') || this.is('text') || this.is('image')) items.push(this.item())
    const cels: Cel[] = []
    while (this.is('cel')) cels.push(this.cel())
    expandHoldCels(cels) // `cel … hold {}` → carry the previous cel's poses for unmentioned containers
    const children: Layer[] = []
    while (!this.is('}')) children.push(...this.layer(id)) // nested layers → siblings pointing to `parent`
    this.eat('}')
    if (cels.length) { // poses reference the roster by NAME → we resolve to ids
      const byName = new Map<string, string>(items.map((it): [string, string] => [itemName(it), it.id]).filter(([nm]) => nm !== ''))
      for (const c of cels) for (const p of c.poses) if (p.id.startsWith('@')) p.id = byName.get(p.id.slice(1)) ?? p.id
    }
    const self: Layer = {
      id, name, visible: !hidden, locked, opacity, items,
      ...(cels.length ? { cels } : {}),
      ...(parent ? { parent } : {}),
      ...(isFolder ? { isFolder: true } : {}), ...(collapsed ? { collapsed: true } : {}),
      ...(isMask ? { isMask: true } : {}), ...(maskOff ? { maskOff: true } : {}),
      ...(isGuide ? { isGuide: true } : {}), ...(orientToGuide ? { orientToGuide: true } : {}),
    }
    return [self, ...children]
  }
  private timeline(): Timeline {
    this.eat('timeline')
    const fps = this.num()
    const dur = this.num()
    return { fps, durationFrames: dur, tracks: [] }
  }
  private cel(): Cel {
    this.eat('cel')
    const frame = this.num()
    let tween = false, shapeTween = false, hold = false, ease: Easing | undefined
    for (;;) {
      if (this.is('tween')) { this.next(); tween = true }
      else if (this.is('morph')) { this.next(); shapeTween = true }
      else if (this.is('hold')) { this.next(); hold = true } // carry the previous cel's poses forward (compile-time)
      else if (this.is('ease')) { this.next(); ease = this.easing() }
      else break
    }
    this.eat('{')
    const poses: Pose[] = []
    let matter: Region[] | undefined
    while (!this.is('}')) {
      if (this.is('pose')) poses.push(this.pose())
      else if (this.is('matter')) matter = this.matter()
      else throw new Error(`pose/matter expected: "${this.peek()?.v ?? 'end'}"`)
    }
    this.eat('}')
    // `hold` is transient (compile-time sugar) → stripped by expandHoldCels after the layer's cels are parsed.
    return { frame, poses, ...(tween ? { tween } : {}), ...(shapeTween ? { shapeTween } : {}), ...(ease ? { ease } : {}), ...(matter ? { matter } : {}), ...(hold ? { hold } : {}) } as Cel
  }
  private pose(): Pose {
    this.eat('pose')
    const name = this.str()
    const transform = (this.is('at') || this.is('matrix')) ? this.transform() : undefined
    let opacity: number | undefined, tint: Tint | undefined, spin: 'cw' | 'ccw' | undefined, turns: number | undefined, filters: Filter[] | undefined
    let rotate: number | undefined, scaleX: number | undefined, scaleY: number | undefined
    for (;;) {
      if (this.is('opacity')) { this.next(); opacity = this.num() }
      else if (this.is('rotate')) { this.next(); rotate = this.num() } // DEGREES, around the body's pivot
      else if (this.is('scale')) { this.next(); scaleX = scaleY = this.num() }
      else if (this.is('scaleX')) { this.next(); scaleX = this.num() }
      else if (this.is('scaleY')) { this.next(); scaleY = this.num() }
      else if (this.is('tint')) { this.next(); tint = this.tintValue() }
      else if (this.is('spin')) { this.next(); spin = this.next().v as 'cw' | 'ccw' }
      else if (this.is('turns')) { this.next(); turns = this.num() }
      else if (this.is('filter')) { (filters ??= []).push(this.filter()) }
      else break
    }
    return { id: '@' + name, ...(transform ? { transform } : {}), ...(rotate != null ? { rotate } : {}), ...(scaleX != null ? { scaleX } : {}), ...(scaleY != null ? { scaleY } : {}), ...(opacity != null ? { opacity } : {}), ...(tint ? { tint } : {}), ...(spin ? { spin } : {}), ...(turns ? { turns } : {}), ...(filters ? { filters } : {}) }
  }
  private matter(): Region[] {
    this.eat('matter'); this.eat('{')
    const out: Region[] = []
    while (!this.is('}')) out.push(this.region())
    this.eat('}')
    return out
  }
  private easing(): Easing {
    if (this.is('cubic')) {
      this.next(); this.eat('(')
      const a = this.num(); this.eat(','); const b = this.num(); this.eat(','); const c = this.num(); this.eat(','); const d = this.num()
      this.eat(')')
      return { cubic: [a, b, c, d] }
    }
    return this.next().v as Easing
  }
  private item(): Item {
    if (this.is('path') || this.is('circle') || this.is('ellipse') || this.is('rect')) return this.region()
    if (this.is('group')) return this.group()
    if (this.is('instance')) return this.instance()
    if (this.is('text')) return this.text()
    if (this.is('image')) return this.image()
    throw new Error(`unexpected item: "${this.peek()?.v ?? 'end'}"`)
  }
  private isNum() { return this.peek()?.k === 'num' }
  /** Geometry of a region: `path "d"` or a primitive (sugar, normalized to path on output). */
  private shapePath(): Path {
    if (this.is('circle')) { this.eat('circle'); const cx = this.num(), cy = this.num(), r = this.num(); return circlePath(cx, cy, r) }
    if (this.is('ellipse')) { this.eat('ellipse'); const cx = this.num(), cy = this.num(), rx = this.num(), ry = this.num(); return ellipsePath(cx, cy, rx, ry) }
    if (this.is('rect')) {
      this.eat('rect'); const x = this.num(), y = this.num(), w = this.num(), h = this.num()
      // optional positional corner radii: `rect x y w h` · `… r` (uniform) · `… rx ry`
      const rx = this.isNum() ? this.num() : 0
      const ry = this.isNum() ? this.num() : rx
      return rectPath(x, y, w, h, rx, ry)
    }
    this.eat('path'); return parsePathData(this.str())
  }
  private region(): Region {
    const path = this.shapePath()
    // optional `as "<id>"`: a STABLE name making the shape addressable (e.g. `text … along "<id>"`).
    let name: string | undefined
    if (this.is('as')) {
      this.next()
      name = this.str()
      if (!TEXT_ID.test(name)) throw new Error(`"as" invalid id: "${name}" (letters, digits, "_", "-"; starts with a letter or "_"; 64 max)`)
    }
    let paint: Paint | undefined
    let noFill = false
    let stroke: Region['stroke']
    let opacity: number | undefined
    let noHit = false
    let filters: Filter[] | undefined
    let color = '#000000'
    let fillParam: string | undefined, strokeParam: string | undefined
    // `fill`/`stroke` accept a bare identifier = a symbol COLOR param ref (not a #color, linear/radial, none).
    const isParamRef = () => { const k = this.peek(); return !!k && k.k === 'id' && k.v !== 'linear' && k.v !== 'radial' && k.v !== 'none' }
    for (;;) {
      if (this.is('nofill')) { this.next(); noFill = true }
      else if (this.is('filter')) { (filters ??= []).push(this.filter()) }
      else if (this.is('fill')) {
        this.next()
        if (isParamRef()) { fillParam = this.next().v }
        else { paint = this.paint(); color = paintColor(paint) }
      }
      else if (this.is('stroke')) {
        this.next()
        let sp: Paint
        if (isParamRef()) { strokeParam = this.next().v; sp = { type: 'solid', color: '#000000' } } // resolved per instance
        else sp = this.paint()
        const w = this.num()
        const st: NonNullable<Region['stroke']> = { width: w, paint: sp }
        for (;;) {
          if (this.is('cap')) { this.next(); st.cap = this.next()!.v as NonNullable<Region['stroke']>['cap'] }
          else if (this.is('join')) { this.next(); st.join = this.next()!.v as NonNullable<Region['stroke']>['join'] }
          else if (this.is('miter')) { this.next(); st.miterLimit = this.num() }
          else if (this.is('dash')) { this.next(); const ds: number[] = [this.num()]; while (this.is(',')) { this.eat(','); ds.push(this.num()) } st.dash = ds }
          else break
        }
        stroke = st; if (!paint && !noFill && !strokeParam) color = paintColor(sp)
      }
      else if (this.is('opacity')) { this.next(); opacity = this.num() }
      else if (this.is('nohit')) { this.next(); noHit = true }
      else break
    }
    const r: Region = { id: uid('r'), color, path }
    if (name) r.name = name
    if (paint && paint.type !== 'solid') r.paint = paint
    if (fillParam) r.fillParam = fillParam
    if (strokeParam) r.strokeParam = strokeParam
    if (noFill) r.noFill = true
    if (stroke) r.stroke = stroke
    if (opacity != null) r.opacity = opacity
    if (filters) r.filters = filters
    if (noHit) r.noHit = true
    return r
  }
  private group(): Group {
    this.eat('group')
    const name = this.str()
    const transform = this.transform(name)
    const a = this.poseAttrs()
    this.eat('{')
    const timeline = this.is('timeline') ? this.timeline() : undefined
    const layers: Layer[] = []
    while (!this.is('}')) layers.push(...this.layer())
    this.eat('}')
    return { id: uid('g'), kind: 'group', name, transform, layers, ...leafAttrs(a), ...(a.hitbox ? { hitbox: a.hitbox } : {}), ...(a.clip ? { clip: a.clip } : {}), ...exprAttr(a), ...(timeline ? { timeline } : {}) }
  }
  private instance(): Instance {
    this.eat('instance')
    const symName = this.str()
    let name = symName
    if (this.is('as')) { this.next(); name = this.str() }
    const transform = this.transform(name)
    const a = this.poseAttrs()
    const params = this.is('{') ? this.callSiteParams() : undefined // `instance "X" { hull = #fff, wave = 1.5 }`
    // `synced` is the default → store a `playback` only for the non-default modes (keeps round-trips minimal).
    const playback = a.playback && a.playback.mode !== 'synced' ? a.playback : undefined
    return { id: uid('i'), kind: 'instance', name, transform, symbolId: '@' + symName, ...leafAttrs(a), ...(a.clip ? { clip: a.clip } : {}), ...exprAttr(a), ...(playback ? { playback } : {}), ...(params ? { params } : {}) }
  }
  /** Call-site values for a symbol's exposed params: `{ name = <literal> [, name2 = …] }` (single-token literals). */
  private callSiteParams(): Record<string, string> {
    this.eat('{')
    const out: Record<string, string> = {}
    while (!this.is('}')) {
      const key = this.next().v
      this.eat('=')
      out[key] = this.next().v
      if (this.is(',')) this.next()
    }
    this.eat('}')
    return out
  }
  private text(): Text {
    this.eat('text')
    const content = this.str()
    // optional `as "<id>"`: sets a STABLE id (cf. text("…") / host). Asymmetry deliberately kept with
    // `instance … as "<name>"` which sets the NAME (objects refer to it by name; texts by id).
    let id: string | undefined
    if (this.is('as')) {
      this.next()
      id = this.str()
      if (!TEXT_ID.test(id)) throw new Error(`"as" invalid id: "${id}" (letters, digits, "_", "-"; starts with a letter or "_"; 64 max)`)
    }
    const transform = this.transform(id) // texts refer by id (cf. as "<id>")
    let font = 'sans-serif', size = 16, align: Text['align'] = 'left', lineHeight = 1.2, color = '#000000'
    let weight: number | undefined, italic = false, box = { w: 0, h: 0 }
    let wrap = false, bind: string | undefined, decimals: number | undefined
    let stroke: Text['stroke']
    let alongRef: string | undefined, alongInline: string | undefined, startFrac: number | undefined // text-on-path (RFC)
    let side: 'over' | 'under' | undefined, spacing: number | undefined
    let startExpr: string | undefined, spacingExpr: string | undefined // animated channels (Phase 3): `start "<expr>"` etc.
    for (;;) {
      // `along "<id>"` follows a NAMED shape's outline (baked post-parse); `along path "<d>"` follows inline
      // SVG data (baked literally, here). `side`/`spacing` tune the run; a quoted `start`/`spacing` is an
      // animated expression (marquee / eased tracking), a bare number is a literal.
      if (this.is('along')) { this.next(); if (this.is('path')) { this.next(); alongInline = this.str() } else alongRef = this.str() }
      else if (this.is('start')) { this.next(); if (this.peek()?.k === 'str') startExpr = this.str(); else startFrac = this.num() }
      else if (this.is('side')) { this.next(); const v = this.next().v; if (v !== 'over' && v !== 'under') throw new Error(`text: "side" expects over|under, got "${v}"`); side = v }
      else if (this.is('spacing')) { this.next(); if (this.peek()?.k === 'str') spacingExpr = this.str(); else spacing = this.num() }
      else if (this.is('font')) { this.next(); font = this.str() }
      else if (this.is('size')) { this.next(); size = this.num() }
      else if (this.is('align')) { this.next(); align = this.str() as Text['align'] }
      else if (this.is('line')) { this.next(); lineHeight = this.num() }
      else if (this.is('color')) { this.next(); color = this.next().v }
      else if (this.is('stroke')) {
        // Mirrors the region stroke grammar: `stroke <paint> <width> [cap …] [join …] [miter …] [dash …]`.
        this.next(); const sp = this.paint(); const w = this.num()
        const st: NonNullable<Text['stroke']> = { width: w, paint: sp }
        for (;;) {
          if (this.is('cap')) { this.next(); st.cap = this.next()!.v as NonNullable<Text['stroke']>['cap'] }
          else if (this.is('join')) { this.next(); st.join = this.next()!.v as NonNullable<Text['stroke']>['join'] }
          else if (this.is('miter')) { this.next(); st.miterLimit = this.num() }
          else if (this.is('dash')) { this.next(); const ds: number[] = [this.num()]; while (this.is(',')) { this.eat(','); ds.push(this.num()) } st.dash = ds }
          else break
        }
        stroke = st
      }
      else if (this.is('bold')) { this.next(); weight = 700 }
      else if (this.is('italic')) { this.next(); italic = true }
      else if (this.is('box')) { this.next(); box = { w: this.num(), h: this.num() } }
      else if (this.is('wrap')) { this.next(); wrap = true }
      else if (this.is('bind')) { this.next(); bind = this.str() }
      else if (this.is('decimals')) { this.next(); decimals = this.num() }
      else break
    }
    const a = this.poseAttrs()
    const t: Text = { id: id ?? uid('t'), kind: 'text', name: content || 'Text', ...(id !== undefined ? { idExplicit: true } : {}), transform, content, font, size, align, lineHeight, color, ...(stroke ? { stroke } : {}), ...(weight ? { weight } : {}), ...(italic ? { italic } : {}), box, ...(wrap ? { wrap: true } : {}), ...(bind ? { bind } : {}), ...(decimals != null ? { decimals } : {}), ...leafAttrs(a), ...exprAttr(a) }
    // text-on-path: inline `along path "<d>"` is baked here (literal — author owns orientation); a named
    // `along "<id>"` defers to resolveTextPaths (forward refs allowed). `side over`/`spacing 0` = defaults → dropped.
    const tpAttrs = { ...(startFrac != null ? { start: startFrac } : {}), ...(side === 'under' ? { side } : {}), ...(spacing ? { spacing } : {}), ...(startExpr ? { startExpr } : {}), ...(spacingExpr ? { spacingExpr } : {}) }
    if (alongInline !== undefined) t.textPath = { path: parsePathData(alongInline), ...tpAttrs }
    else if (alongRef !== undefined) this.textPaths.push({ text: t, ref: alongRef, ...tpAttrs })
    return t
  }
  private image(): Image {
    this.eat('image')
    const assetId = this.str()
    const w = this.num(), h = this.num()
    const name = this.is('as') ? (this.next(), this.str()) : 'Image'
    const transform = this.transform(name)
    const a = this.poseAttrs()
    return { id: uid('im'), kind: 'image', name, transform, assetId, w, h, ...leafAttrs(a), ...exprAttr(a) }
  }
  /** Coordinate of an `at`: a number, or the `center` keyword (canvas center on the relevant axis). */
  private coord(isX: boolean): number {
    if (this.is('center')) { this.next(); return isX ? this.cw / 2 : this.ch / 2 }
    return this.num()
  }
  private transform(name?: string): Transform {
    if (this.is('at')) {
      this.next()
      // `at center` alone → canvas center; otherwise `at <x>,<y>` where each coord can be `center`.
      if (this.is('center') && this.t[this.p + 1]?.v !== ',') { this.next(); return { a: 1, b: 0, c: 0, d: 1, e: this.cw / 2, f: this.ch / 2 } }
      const x = this.coord(true); this.eat(','); const y = this.coord(false)
      return { a: 1, b: 0, c: 0, d: 1, e: x, f: y }
    }
    // `align <point> of "Name" [offset dx,dy]`: anchors the origin on a point of the STATIC bbox of Name.
    // Lookahead `of` to NOT capture the text-align attribute (`align left|center|…`), resolved further down.
    if (this.is('align') && this.t[this.p + 2]?.v === 'of') {
      this.next()
      const point = this.next().v
      if (!ANCHOR_POINTS.has(point)) throw new Error(`align: unknown point "${point}" (expected: ${[...ANCHOR_POINTS].join(', ')})`)
      this.eat('of')
      const target = this.str()
      let dx = 0, dy = 0
      if (this.is('offset')) { this.next(); dx = this.num(); this.eat(','); dy = this.num() }
      const tf = { a: 1, b: 0, c: 0, d: 1, e: 0, f: 0 } // resolved in place (shared ref) after the parse → cf. resolveAligns
      this.aligns.push({ tf, point, target, dx, dy, name })
      return tf
    }
    if (this.is('matrix')) {
      this.next(); this.eat('(')
      const v = [0, 0, 0, 0, 0, 0]
      for (let k = 0; k < 6; k++) { v[k] = this.num(); if (k < 5) this.eat(',') }
      this.eat(')')
      return { a: v[0], b: v[1], c: v[2], d: v[3], e: v[4], f: v[5] }
    }
    return { a: 1, b: 0, c: 0, d: 1, e: 0, f: 0 }
  }
  private poseAttrs(): ParsedAttrs {
    const a: ParsedAttrs = {}
    for (;;) {
      if (this.is('opacity')) { this.next(); a.opacity = this.num() }
      else if (this.is('pivot')) { this.next(); const x = this.num(); this.eat(','); const y = this.num(); a.pivot = { x, y } }
      else if (this.is('tint')) { this.next(); a.tint = this.tintValue() }
      else if (this.is('filter')) { (a.filters ??= []).push(this.filter()) }
      else if (this.is('expr')) { this.next(); const ch = this.next().v as ExprChannel; const ex = this.str(); (a.expressions ??= {})[ch] = ex }
      else if (this.is('nohit')) { this.next(); a.noHit = true }
      else if (this.is('blend')) { this.next(); a.blend = this.next().v as BlendMode }
      else if (this.is('hitbox')) { this.next(); const w = this.num(); const h = this.num(); a.hitbox = { w, h } }
      else if (this.is('clip')) { this.next(); const x = this.num(); const y = this.num(); const w = this.num(); const h = this.num(); a.clip = { x, y, w, h } }
      // Instance playback mode (Flash symbol models) — only meaningful on an `instance`; ignored elsewhere.
      // `loop` = independent MovieClip clock; `once` = play-through-and-hold; `synced` = default (no-op).
      else if (this.is('loop')) { this.next(); a.playback = { mode: 'independent' } }
      else if (this.is('once')) { this.next(); a.playback = { mode: 'once' } }
      else if (this.is('synced')) { this.next(); a.playback = { mode: 'synced' } }
      else break
    }
    return a
  }
  private filter(): Filter {
    this.eat('filter')
    const t = this.next().v
    if (t === 'blur') return { type: 'blur', radius: this.num() }
    if (t === 'shadow') return { type: 'shadow', dx: this.num(), dy: this.num(), blur: this.num(), color: this.next().v }
    if (t === 'glow') return { type: 'glow', blur: this.num(), color: this.next().v }
    return { type: 'adjust', brightness: this.num(), contrast: this.num(), saturate: this.num(), hue: this.num() }
  }
  private paint(): Paint {
    const k = this.peek()
    if (k.k === 'color') { this.next(); return { type: 'solid', color: k.v } }
    if (this.is('linear')) {
      this.next(); this.eat('(')
      const angle = this.num(); this.eat(',')
      const stops = this.stops()
      this.eat(')')
      return { type: 'linear', angle, stops }
    }
    if (this.is('radial')) {
      this.next(); this.eat('(')
      const cx = this.num(); this.eat(','); const cy = this.num(); this.eat(','); const r = this.num(); this.eat(',')
      const stops = this.stops()
      this.eat(')')
      return { type: 'radial', cx, cy, r, stops }
    }
    if (k?.v === 'none') throw new Error('paint expected: "none" — for an unfilled shape write `nofill` (e.g. `path "…" nofill stroke #000 2`), not `fill none`')
    throw new Error(`paint expected: "${k?.v ?? 'end'}" (a color #rrggbb, or linear(…)/radial(…))`)
  }
  private stops(): Stop[] {
    const out: Stop[] = []
    for (;;) {
      const off = this.num(); this.eat(':')
      const k = this.peek()
      if (k?.k === 'color') { this.next(); out.push({ offset: off, color: k.v }) } // literal hex (alpha may be baked: #rrggbbaa)
      else { // a symbol COLOR param ref, optionally with an alpha override: `teinte` / `teinte@0.8`
        const param = this.next().v
        const stop: Stop = { offset: off, color: this.colorDefaults.get(param) ?? '#000000', param }
        if (this.is('@')) { this.next(); stop.alpha = this.num() }
        out.push(stop)
      }
      if (this.is(',')) this.next()
      else break
    }
    return out
  }
  /** `tint <color|param> <amount>` — a literal hex, or a symbol COLOR param ref (resolved per instance). */
  private tintValue(): Tint {
    const k = this.peek()
    if (k?.k === 'color') { this.next(); return { color: k.v, amount: this.num() } }
    const param = this.next().v
    return { color: this.colorDefaults.get(param) ?? '#000000', param, amount: this.num() }
  }
}

// Attributes common to all poseable leaves (opacity/pivot/tint/filters).
type LeafAttrs = { opacity?: number; pivot?: { x: number; y: number }; tint?: Tint; filters?: Filter[]; noHit?: boolean; blend?: BlendMode }
const leafAttrs = (a: ParsedAttrs): LeafAttrs => ({
  ...(a.opacity != null ? { opacity: a.opacity } : {}),
  ...(a.pivot ? { pivot: a.pivot } : {}),
  ...(a.tint ? { tint: a.tint } : {}),
  ...(a.filters ? { filters: a.filters } : {}),
  ...(a.noHit ? { noHit: true } : {}),
  ...(a.blend ? { blend: a.blend } : {}),
})
// Channel expressions: all poseable leaves (group/instance/text/image).
const exprAttr = (a: ParsedAttrs) => (a.expressions ? { expressions: a.expressions } : {})

/** Resolves the `symbolId: '@Name'` (references by name) into real ids, recursively. */
function resolveInstanceNames(symbols: SymbolDef[]): void {
  const byName = new Map(symbols.map((s) => [s.name, s.id]))
  const walk = (items: Item[]) => {
    for (const it of items) {
      if (isInstance(it) && it.symbolId.startsWith('@')) it.symbolId = byName.get(it.symbolId.slice(1)) ?? it.symbolId
      if (isGroup(it)) it.layers.forEach((l) => walk(l.items))
    }
  }
  symbols.forEach((s) => s.layers.forEach((l) => walk(l.items)))
}

/** Parses a `.flat` library → symbols + folders (ids regenerated; instances resolved by name). */
export function parseFlatLib(src: string): { symbols: SymbolDef[]; folders: Folder[] } {
  const parser = new FlatParser(tokenize(src))
  const symbols = parser.parse()
  resolveInstanceNames(symbols)
  return { symbols, folders: parser.parsedFolders }
}

/** Parses a `.flat` library → symbols (ids regenerated; instances resolved by name). */
export function parseFlat(src: string): SymbolDef[] {
  return parseFlatLib(src).symbols
}
