// ─────────────────────────────────────────────────────────────────────────────
//  stdlib.generated.ts — AUTO-GENERATED by scripts/gen-stdlib.ts — DO NOT EDIT BY HAND.
//  Pre-compiled stdlib packages (DSL → AST). The runtime consumes them directly, without a parser.
//  Regenerate: pnpm --filter @flatkit/engine gen:stdlib  (then verified by stdlib.generated.test.ts).
// ─────────────────────────────────────────────────────────────────────────────
import type { FuncDef } from '@flatkit/types'

export const PACKAGE_FUNCS: Record<string, FuncDef[]> = {
  "collision": [
    {
      "name": "boxHit",
      "params": [
        "ax",
        "ay",
        "bx",
        "by",
        "hw",
        "hh"
      ],
      "kind": "value",
      "expr": "abs(ax - bx) < hw && abs(ay - by) < hh"
    },
    {
      "name": "dist",
      "params": [
        "ax",
        "ay",
        "bx",
        "by"
      ],
      "kind": "value",
      "expr": "hypot(ax - bx, ay - by)"
    },
    {
      "name": "near",
      "params": [
        "ax",
        "ay",
        "bx",
        "by",
        "r"
      ],
      "kind": "value",
      "expr": "hypot(ax - bx, ay - by) < r"
    }
  ],
  "easing": [
    {
      "name": "easeIn",
      "params": [
        "t"
      ],
      "kind": "value",
      "expr": "t * t"
    },
    {
      "name": "easeOut",
      "params": [
        "t"
      ],
      "kind": "value",
      "expr": "1 - (1 - t) * (1 - t)"
    },
    {
      "name": "easeInOut",
      "params": [
        "t"
      ],
      "kind": "value",
      "expr": "t < 0.5 ? 2 * t * t : 1 - 2 * (1 - t) * (1 - t)"
    },
    {
      "name": "smooth",
      "params": [
        "t"
      ],
      "kind": "value",
      "expr": "t * t * (3 - 2 * t)"
    }
  ],
  "gesture": [
    {
      "name": "snap",
      "params": [
        "v",
        "step"
      ],
      "kind": "value",
      "expr": "round(v / step) * step"
    },
    {
      "name": "snapTo",
      "params": [
        "v",
        "target",
        "r"
      ],
      "kind": "value",
      "expr": "abs(v - target) < r ? target : v"
    },
    {
      "name": "railT",
      "params": [
        "px",
        "py",
        "ax",
        "ay",
        "bx",
        "by"
      ],
      "kind": "value",
      "expr": "clamp(((px - ax) * (bx - ax) + (py - ay) * (by - ay)) / ((bx - ax) * (bx - ax) + (by - ay) * (by - ay)), 0, 1)"
    },
    {
      "name": "railX",
      "params": [
        "px",
        "py",
        "ax",
        "ay",
        "bx",
        "by"
      ],
      "kind": "value",
      "expr": "ax + (bx - ax) * railT(px, py, ax, ay, bx, by)"
    },
    {
      "name": "railY",
      "params": [
        "px",
        "py",
        "ax",
        "ay",
        "bx",
        "by"
      ],
      "kind": "value",
      "expr": "ay + (by - ay) * railT(px, py, ax, ay, bx, by)"
    },
    {
      "name": "angle",
      "params": [
        "cx",
        "cy",
        "px",
        "py"
      ],
      "kind": "value",
      "expr": "atan2(py - cy, px - cx)"
    },
    {
      "name": "inZone",
      "params": [
        "px",
        "py",
        "x",
        "y",
        "w",
        "h"
      ],
      "kind": "value",
      "expr": "px >= x && px <= x + w && py >= y && py <= y + h"
    }
  ],
  "feedback": [
    {
      "name": "lift",
      "params": [
        "h"
      ],
      "kind": "value",
      "expr": "h ? 1.06 : 1"
    },
    {
      "name": "dim",
      "params": [
        "h"
      ],
      "kind": "value",
      "expr": "h ? 0.85 : 1"
    },
    {
      "name": "tilt",
      "params": [
        "g"
      ],
      "kind": "value",
      "expr": "g ? 0.94 : 1"
    },
    {
      "name": "sink",
      "params": [
        "g"
      ],
      "kind": "value",
      "expr": "g ? 2 : 0"
    },
    {
      "name": "shake",
      "params": [
        "bad",
        "t"
      ],
      "kind": "value",
      "expr": "bad ? sin(t * 40) * 4 : 0"
    },
    {
      "name": "pulse",
      "params": [
        "since",
        "dur"
      ],
      "kind": "value",
      "expr": "clamp(1 - (time - since) / dur, 0, 1)"
    }
  ]
}
