// -----------------------------------------------------------------------------
//  programDoc.ts — PURE bridge Doc <-> "scope program" (text) + lint of a whole Doc.
//
//  Both the editor AND the CLI need to rebuild the DSL text of a scope (to display it,
//  or to lint it) and to assemble the lint context (variables/labels/functions/objects)
//  FROM a Doc — without depending on the React store. Everything lives here, pure and testable:
//   • `scopeProgram`     : Doc fragments -> program text of a scope (round-trip via printUnits);
//   • `docLintContext`   : Doc + scope -> LintContext (known names);
//   • `lintDoc` / report : semantic lint of ALL the scopes of a Doc (scene + symbols).
//  -> the CLI gains a `flatc --check`, the editor stops duplicating the logic.
// -----------------------------------------------------------------------------
import type { Doc, EditFrame, Group, Instance } from '@flatkit/types'
import { printUnits, type Diagnostic } from '@flatkit/engine/dsl'
import { joinScopeProgram, scopeRegions } from './scopeProgram'
import { functionsToUnits, importsToUnits, objectToUnits, timelineToUnits, variablesToUnits } from '@flatkit/engine/scriptDoc'
import { contextLayers, getScopeTimeline, isContainer, isGroup, isInstance, isText, isImage, isPoseable, isRegion } from '@flatkit/engine/layers'
import { importedFunctions } from '@flatkit/engine/stdlib'
import { EXPR_CHANNELS } from '@flatkit/engine/timeline'
import { objectNames } from '@flatkit/engine/sceneRefs'
import { behaviorRegions } from '@flatkit/engine/flatFormat'
import { itemBBox, dropZoneBounds, transformBBox } from '@flatkit/engine/groups'
import { IDENTITY, apply, compose } from '@flatkit/engine/transform'
import { makePathSampler } from '@flatkit/engine/path'
import { bboxIntersects } from '@flatkit/engine/bbox'
import { lint, localVariables, type LintContext } from './lint'
import { forEachAction, forEachExpression } from './docWalk'
import { parseUnits } from '@flatkit/engine/dsl'
import type { Image, Item, Layer, ParamDef, SymbolDef, Text, Transform } from '@flatkit/types'

/** Rebuilds the "program" text of a scope (imports + variables + functions + scene cycle
 *  + one `object "Name" { … }` block per scripted container with a unique name). Pure, round-trip via printUnits. */
export function scopeProgram(doc: Doc, editPath: EditFrame[] = []): string {
  const atRoot = editPath.length === 0
  const items = contextLayers(doc, editPath).flatMap((l) => l.items)
  const nameCount = new Map<string, number>()
  for (const it of items) if (isContainer(it) && it.name) nameCount.set(it.name, (nameCount.get(it.name) ?? 0) + 1)
  const scripted = (it: Group | Instance) => !!doc.interactions?.some((i) => i.targetId === it.id) || !!doc.interactors?.some((i) => i.targetId === it.id) || !!(it.expressions && Object.keys(it.expressions).length)
  const objects = items
    .filter((it): it is Group | Instance => isContainer(it) && !!it.name && nameCount.get(it.name) === 1 && scripted(it))
    .map((it) => ({ name: it.name, body: printUnits(objectToUnits(it.id, doc.interactions, it.expressions, doc.interactors)) }))
  const imports = atRoot ? printUnits(importsToUnits(doc.imports)) : ''
  // A local package (`use "physics"` -> physics.flatink) is inlined TWICE into doc.functions: `tick` and the
  // qualified alias `physics.tick` (so both call forms resolve). The alias is not authored source and has NO
  // syntax (`fn physics.tick(s) = …` does not parse) -> never re-emit it, or the reconstructed program fails
  // to parse and `--check` reports phantom errors. The alias stays in `doc.functions`, so `docLintContext`
  // still knows `physics.tick` as a callable name.
  const funcs = atRoot ? printUnits(functionsToUnits((doc.functions ?? []).filter((f) => !f.name.includes('.')))) : ''
  const globals = atRoot ? printUnits(variablesToUnits(doc.variables)) : ''
  const scene = printUnits(timelineToUnits(getScopeTimeline(doc, editPath)))
  const head = [imports, globals, funcs, scene].filter((t) => t.trim()).join('\n\n')
  return joinScopeProgram(head, objects)
}

/** Lint context of a scope: known names (variables, labels, functions, objects) drawn from the Doc.
 *  `extraVars` = variables assigned in the OTHER scopes (FlatInk variables are GLOBAL -> known
 *  everywhere; avoids a false "unknown variable" on a var written elsewhere, e.g. generated by `match`). */
export function docLintContext(doc: Doc, editPath: EditFrame[] = [], extraVars?: Iterable<string>): LintContext {
  return {
    // A symbol's own `params` (and state params) are injected into its instance scope at runtime, so they are
    // valid variables in ITS `expr` -- add them, but ONLY to that symbol's scope (resolved from `editPath`),
    // never globally, so a param named in symbol A can't mask a real typo of the same name in symbol B.
    variables: [...Object.keys(doc.variables ?? {}), ...(extraVars ?? []), ...scopeSymbolParams(doc, editPath)],
    labels: (getScopeTimeline(doc, editPath)?.labels ?? []).map((l) => l.name),
    functions: [...(doc.functions ?? []).map((f) => f.name), ...importedFunctions(doc.imports).map((f) => f.name)],
    objects: objectNames(contextLayers(doc, editPath)),
  }
}

/** Names exposed as variables by the symbol of `editPath` (its `params` + state params), or `[]` for the
 *  scene scope / an unresolved path. Mirrors the per-instance scope the runtime and `--preview` build. */
function scopeSymbolParams(doc: Doc, editPath: EditFrame[]): string[] {
  const frame = [...editPath].reverse().find((f): f is Extract<EditFrame, { kind: 'symbol' }> => f.kind === 'symbol')
  const sym = frame ? doc.symbols.find((s) => s.id === frame.symbolId) : undefined
  if (!sym) return []
  return [...(sym.params ?? []).map((p) => p.name), ...(sym.states ?? []).map((s) => s.param)]
}

/** All the scopes of a Doc: the scene (root) + each symbol of the library. */
function scopes(doc: Doc): { label: string; editPath: EditFrame[] }[] {
  return [{ label: 'scene', editPath: [] }, ...doc.symbols.map((s) => ({ label: s.name, editPath: [{ kind: 'symbol' as const, symbolId: s.id, name: s.name }] }))]
}

/** Union of the variables ASSIGNED in ALL the scopes (scene + symbols). FlatInk variables are
 *  global -> a var written in one scope is legitimate in the others (cross-scope reads). */
export function allScopeVariables(doc: Doc): string[] {
  const set = new Set<string>()
  for (const { editPath } of scopes(doc))
    for (const r of scopeRegions(scopeProgram(doc, editPath)))
      for (const v of localVariables(parseUnits(r.body).units)) set.add(v)
  return [...set]
}

/** Readable name of an item by id (for the messages). */
function itemNameById(doc: Doc, id: string): string | null {
  let found: string | null = null
  const walk = (layers: { items: import('@flatkit/types').Item[] }[]) => {
    for (const l of layers) for (const it of l.items) {
      if (found) return
      if ('name' in it && it.id === id) { found = it.name ?? null; return }
      if (isGroup(it)) walk(it.layers)
    }
  }
  walk(doc.layers)
  return found
}

const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\-]/g, '\\$&')

/** Value functions reachable in this Doc whose body reads the LOOP-WRAPPED `time`, directly or through
 *  another such function. Only `kind: 'value'` matters — a `proc` is not callable from a channel expression.
 *  Fixpoint, so `fn a(t) = b(t)` inherits from `b`. Qualified aliases (`feedback.pulse`) are kept: an author
 *  may call either form. */
function functionsReadingTime(doc: Doc): string[] {
  const defs = [...(doc.functions ?? []), ...importedFunctions(doc.imports)].filter((f) => f.kind === 'value')
  const reads = new Set<string>()
  for (;;) {
    const before = reads.size
    for (const f of defs) {
      if (reads.has(f.name)) continue
      const body = f.expr
      // A parameter NAMED `time` would shadow the runtime scalar — then the body's `time` is just an argument.
      if (!f.params.includes('time') && /\btime\b/.test(body)) { reads.add(f.name); continue }
      for (const other of reads) if (new RegExp(`\\b${escapeRe(other)}\\s*\\(`).test(body)) { reads.add(f.name); break }
    }
    if (reads.size === before) return [...reads]
  }
}

/** Top-level arguments of every `name(…)` call in `src`. Depth-aware, so a nested call keeps its own
 *  commas: `pulse(max(a, 0), 1)` reads as two arguments, not three. */
function callArguments(src: string, name: string): string[][] {
  const out: string[][] = []
  const re = new RegExp(`(?<![\\w.])${escapeRe(name)}\\s*\\(`, 'g')
  let m: RegExpExecArray | null
  while ((m = re.exec(src))) {
    const args: string[] = []
    let depth = 1
    let start = m.index + m[0].length
    let i = start
    for (; i < src.length; i++) {
      const c = src[i]
      if (c === '(') depth++
      else if (c === ')') { depth--; if (depth === 0) break }
      else if (c === ',' && depth === 1) { args.push(src.slice(start, i)); start = i + 1 }
    }
    args.push(src.slice(start, i))
    out.push(args.map((a) => a.trim()))
  }
  return out
}

/** Which argument of a feedback function is an INSTANT (a timestamp compared against `clock`):
 *  `pulse(since, dur)` → the 1st; `shake(bad, t)` → the 2nd (the 1st is the flag). */
const INSTANT_ARG: Record<string, number> = { pulse: 0, shake: 1 }

/** Variables whose value is captured from `time` (`doneAt = time`) — the pre-0.23 timestamp idiom, back
 *  when `pulse`/`shake` rode `time` too. A capture that already mentions `clock` is the correct one. */
function timeCapturedVars(doc: Doc): Set<string> {
  const out = new Set<string>()
  forEachAction(doc, (a) => {
    if (a.do === 'setVar' && /\btime\b/.test(a.value) && !/\bclock\b/.test(a.value)) out.add(a.name)
  })
  return out
}

/** STRUCTURAL warnings (non-blocking) of a Doc: phantom drop zones, dead variables. */
export function docStructureWarnings(doc: Doc): { scope: string; diag: Diagnostic }[] {
  const out: { scope: string; diag: Diagnostic }[] = []
  // (a) `when dropped on X` whose zone X does not exist (no item named so) -> the handler can never fire.
  const names = new Set(objectNames(doc.layers))
  for (const it of doc.interactions ?? []) {
    if (it.event === 'drop' && it.over && !names.has(it.over)) {
      const who = itemNameById(doc, it.targetId) ?? it.targetId
      out.push({ scope: 'scene', diag: { line: 1, col: 1, severity: 'warning', message: `unknown drop zone "${it.over}" (object "${who}") — no item of the scene carries this name` } })
    }
  }
  // (b) global variable never referenced (declared but not found in any scope) -> probably dead.
  const names0 = Object.keys(doc.variables ?? {})
  if (names0.length) {
    // Modifier targets are NOT emitted into scopeProgram (to avoid double-linting them, cf. docModifierWarnings),
    // so collect them here too — else a global used ONLY by a `spring`/`smooth` target reads as "never used".
    const modTargets: string[] = []
    const collectMods = (items: Item[]): void => {
      for (const it of items) {
        if (isPoseable(it) && it.modifiers) for (const ch of EXPR_CHANNELS) { const mm = it.modifiers[ch]; if (mm) modTargets.push(mm.target) }
        if (isGroup(it)) for (const l of it.layers) collectMods(l.items)
      }
    }
    for (const l of doc.layers) collectMods(l.items)
    for (const s of doc.symbols ?? []) for (const l of s.layers) collectMods(l.items)
    const allText = [...scopes(doc).map(({ editPath }) => scopeProgram(doc, editPath)), ...modTargets].join('\n')
    for (const name of names0) {
      const m = allText.match(new RegExp(`(?<![\\w-])${escapeRe(name)}(?![\\w-])`, 'g'))
      if ((m?.length ?? 0) <= 1) out.push({ scope: 'scene', diag: { line: 1, col: 1, severity: 'warning', message: `global variable "${name}" never used (declared, but neither read nor written)` } })
    }
  }
  // (b bis) An `instance "X"` that resolved to NO symbol. Compilation keeps the unresolved `@X` marker all
  //     the way into the .flatpack, the instance draws nothing, and everything else about the file looks
  //     fine — the same family as the phantom drop zone above: a name that points at nothing. Only a
  //     warning: compiling a program on its own and supplying its libraries later is a legitimate
  //     workflow, and it must keep exiting 0.
  const missing = new Set<string>()
  const scanRefs = (items: Item[]): void => {
    for (const it of items) {
      if (isInstance(it) && it.symbolId.startsWith('@')) missing.add(it.symbolId.slice(1))
      if (isGroup(it)) for (const l of it.layers) scanRefs(l.items)
    }
  }
  for (const l of doc.layers) scanRefs(l.items)
  for (const s of doc.symbols ?? []) for (const l of s.layers) scanRefs(l.items)
  if (missing.size) {
    const names = [...missing].map((n) => `"${n}"`).join(', ')
    out.push(warn(`instance resolves to no symbol: ${names} — nothing is drawn where it stands. Pass the .flat library that defines it (\`flatc <program> <lib.flat>\`, or place it beside the program), or fix the name.`))
  }

  // (c) `time` reaching a channel expression + a SHORT looping timeline → the motion JUMPS on each loop
  //     (`time = frame/fps` resets to 0 every `durationFrames`). The monotone `clock` never wraps.
  //     A `time` reached THROUGH A FUNCTION counts: the costliest version of this trap was
  //     `opacity = pulse(doneAt, 0.9)`, where the wrapping clock sat in the callee's body and the channel
  //     text held no `time` at all — so a warning that only grepped the channel said nothing whatsoever.
  const dur = doc.timeline?.durationFrames ?? 60
  const fps = doc.timeline?.fps ?? 24
  if (dur <= 120) { // ≤ 5 s @24fps: short enough that the reset is visible as a periodic jump
    const viaFn = functionsReadingTime(doc)
    const culprits = new Set<string>()
    const scan = (layers: Layer[]) => {
      for (const l of layers) for (const it of l.items) {
        if (isPoseable(it) && it.expressions) for (const k in it.expressions) {
          const expr = it.expressions[k as keyof typeof it.expressions] ?? ''
          if (/\btime\b/.test(expr)) culprits.add('`time`')
          for (const fn of viaFn) if (new RegExp(`\\b${escapeRe(fn)}\\s*\\(`).test(expr)) culprits.add(`\`${fn}()\`` + ' (which reads `time`)')
        }
        if (isGroup(it)) scan(it.layers)
      }
    }
    scan(doc.layers)
    if (culprits.size) {
      const secs = Math.round((dur / fps) * 10) / 10
      out.push(warn(`a channel expression uses ${[...culprits].join(' and ')}, but the timeline loops every ${secs}s (durationFrames ${dur}) — \`time\` resets each loop, so the motion jumps (a one-shot ramp REPLAYS forever). Use the monotone \`clock\` (never wraps), drive it by \`frame/${dur}\`, or set a longer \`timeline\`.`))
    }
  }
  // (d) An instant captured on `time` and handed to `pulse`/`shake`. Both ride the MONOTONE `clock`, so
  //     `clock - since` grows without bound and the ramp NEVER fires. Unlike (c) this is loop-LENGTH
  //     independent — the two axes never meet however long the timeline is — and it is entirely SILENT:
  //     nothing jumps, nothing blinks, and (c) itself stays quiet because the channel text holds no `time`.
  //     The 0.21 → 0.23 migration trap: back then `pulse` rode `time` and the mismatch at least showed.
  const captured = timeCapturedVars(doc)
  if (captured.size) {
    const readers = new Map<string, Set<string>>() // variable → the feedback functions reading it as an instant
    forEachExpression(doc, (expr) => {
      for (const fnName of Object.keys(INSTANT_ARG)) {
        for (const args of callArguments(expr, fnName)) {
          const arg = args[INSTANT_ARG[fnName]]
          if (!arg) continue
          // The name may sit INSIDE the argument (`pulse(max(doneAt, 0), 1)`) — match it as a whole word.
          for (const v of captured) {
            if (!new RegExp(`(?<![\\w-])${escapeRe(v)}(?![\\w-])`).test(arg)) continue
            const seen = readers.get(v) ?? new Set<string>()
            seen.add(fnName)
            readers.set(v, seen)
          }
        }
      }
    })
    for (const [v, fns] of readers) {
      const who = [...fns].map((f) => `\`${f}()\``).join(' and ')
      out.push(warn(`"${v}" is captured on \`time\` but read as an INSTANT by ${who}, which compares it against the monotone \`clock\` — the two axes never meet, so the ramp never fires and nothing on screen says so. Capture it with \`clock\` instead: \`${v} = clock\`.`))
    }
  }
  out.push(...docPaintParamWarnings(doc))
  out.push(...docCelLayerWarnings(doc))
  out.push(...docLayoutWarnings(doc))
  return out
}

/**
 * SILENT DROPS in a cel layer. `resolveLayerAt` draws exactly two things: the current cel's `matter`, and
 * the containers that cel POSES — never the layer's other roster items. Three ways to author a layer that
 * compiles, renders an empty frame, and says nothing:
 *   (a) a bare shape (`path`/`circle`/`rect`/…) sitting in a layer that has cels — it belongs inside a
 *       cel's `matter { … }` (frame-by-frame drawing) or on a cel-less layer (static decor);
 *   (b) a `pose "X"` naming no roster item (the parser leaves such a pose id as `@X`) — poses nothing;
 *   (c) a roster container/text/image that no cel ever poses — never drawn.
 * All three are the classic "my drawing vanished" bug. Warnings (non-blocking).
 */
export function docCelLayerWarnings(doc: Doc): { scope: string; diag: Diagnostic }[] {
  const out: { scope: string; diag: Diagnostic }[] = []
  const checkScope = (scope: string, layers: Layer[]) => {
    const push = (message: string) => out.push({ scope, diag: { line: 1, col: 1, severity: 'warning', message } })
    const visit = (ls: Layer[]): void => {
      for (const l of ls) {
        if (l.cels?.length) {
          const bare = l.items.filter(isRegion)
          if (bare.length) push(`layer "${l.name}" has cels, so its ${bare.length} bare shape(s) are NEVER drawn — a cel layer draws only the cel's \`matter { … }\` and the containers it poses. Move them into \`cel N { matter { … } }\`, or onto a cel-less layer if they are static.`)
          const posed = new Set<string>()
          for (const c of l.cels) for (const p of c.poses) posed.add(p.id)
          for (const id of posed) if (id.startsWith('@')) push(`layer "${l.name}": \`pose "${id.slice(1)}"\` matches no item of this layer — the pose draws nothing (roster: ${l.items.map(itemLabel).join(', ') || 'empty'}).`)
          for (const it of l.items) if (isPoseable(it) && !posed.has(it.id)) push(`layer "${l.name}": "${itemLabel(it)}" is never posed by a cel — it is never drawn. Add \`pose "${itemLabel(it)}"\` to the cels where it should show.`)
          // Posed, SKIPPED, then posed again: the item blinked out and back. A cel is a full snapshot, so
          // that is the model working as designed — and it is exactly how an exit is written, which is why
          // a FINAL absence says nothing. But a staggered entrance (three things arriving at three
          // moments) needs `hold` on every cel, and forgetting it makes elements vanish mid-run in
          // silence. That omission is what a program-scene animation trips on, every time.
          const cels = [...l.cels].sort((a, b) => a.frame - b.frame)
          for (const it of l.items) {
            if (!isPoseable(it)) continue
            const at = cels.map((c) => c.poses.some((p) => p.id === it.id))
            const first = at.indexOf(true)
            const last = at.lastIndexOf(true)
            // The hole must sit BETWEEN the first and last pose. Absent before the first is a late
            // ENTRANCE, absent after the last is an EXIT — both are how the model is meant to be used.
            const gap = at.findIndex((on, i) => !on && i > first && i < last)
            if (gap >= 0) {
              push(`layer "${l.name}": "${itemLabel(it)}" is posed at cel ${cels[first].frame}, absent at cel ${cels[gap].frame}, then posed again at cel ${cels[last].frame} — a cel is a FULL snapshot, so it disappears in between. Add \`hold\` to the cels that should carry it forward (\`cel ${cels[gap].frame} hold { … }\`), or pose it there.`)
            }
          }
        }
        for (const it of l.items) if (isGroup(it)) visit(it.layers)
      }
    }
    visit(layers)
  }
  checkScope('scene', doc.layers)
  for (const s of doc.symbols) checkScope(s.name, s.layers)
  return out
}

/** A scope's declared `color` param names (the only params usable as a paint color). */
const colorParamNames = (params?: ParamDef[]): Set<string> => new Set((params ?? []).filter((p) => p.type === 'color').map((p) => p.name))

/**
 * A `color` param used as a paint (`fill`/`stroke`, a gradient **stop** `0:teinte@…`, or a `tint`) that the
 * owning symbol does NOT declare → a SILENT "dead recolor" (it falls back to the literal hex, the picker does
 * nothing). Warns per scope, with the param scoped to ITS symbol (the scene declares none). Mirrors how the
 * lint now knows a symbol's params in its `expr`. Non-blocking (a warning), so it never breaks a build.
 */
export function docPaintParamWarnings(doc: Doc): { scope: string; diag: Diagnostic }[] {
  const out: { scope: string; diag: Diagnostic }[] = []
  const checkScope = (scope: string, layers: Layer[], known: Set<string>) => {
    const flag = (param: string, where: string, who?: string) => {
      if (known.has(param)) return
      const hint = known.size ? `declared color params: ${[...known].join(', ')}` : 'this scope declares no color params'
      out.push({ scope, diag: { line: 1, col: 1, severity: 'warning', message: `unknown color param "${param}" in ${where}${who ? ` (${who})` : ''} — ${hint}` } })
    }
    const visit = (it: Item) => {
      const who = 'name' in it ? it.name : undefined
      if (isRegion(it)) {
        if (it.fillParam) flag(it.fillParam, 'a fill', who)
        if (it.strokeParam) flag(it.strokeParam, 'a stroke', who)
        const stops = it.paint && it.paint.type !== 'solid' ? it.paint.stops : []
        for (const s of stops) if (s.param) flag(s.param, 'a gradient stop', who)
      }
      if (isPoseable(it) && it.tint?.param) flag(it.tint.param, 'a tint', who)
      if (isGroup(it)) for (const l of it.layers) for (const c of l.items) visit(c) // a group is the same scope; an instance is a separate symbol (linted on its own pass)
    }
    for (const l of layers) for (const it of l.items) visit(it)
  }
  checkScope('scene', doc.layers, new Set())
  for (const s of doc.symbols) checkScope(s.name, s.layers, colorParamNames((s as SymbolDef).params))
  return out
}

const warn = (message: string): { scope: string; diag: Diagnostic } => ({ scope: 'scene', diag: { line: 1, col: 1, severity: 'warning', message } })
const itemLabel = (it: Item): string => ('name' in it && it.name ? it.name : 'kind' in it ? it.kind : 'path')
/** Mean advance of a proportional glyph at this text's size — the metric both estimators share. */
const glyphAdvance = (t: Text): number => (t.weight && t.weight >= 700 ? 0.56 : 0.52) * t.size

/** Estimated width of the longest line (approximate metric, without canvas). */
function estTextWidth(t: Text): number {
  const advance = glyphAdvance(t)
  let longest = 0
  for (const line of t.content.split('\n')) longest = Math.max(longest, line.length)
  return longest * advance
}

/** Greedy word-wrap of a `wrap` text at its box width — the renderer's own rule (break at spaces, and
 *  only at spaces). Returns the resulting line count and the widest single word, which is what decides
 *  whether anything spills sideways: a word wider than the box has no break point and runs past it. */
function wrapMetrics(t: Text): { lines: number; widestWord: number } {
  const advance = glyphAdvance(t)
  const width = (s: string) => s.length * advance
  let lines = 0
  let widestWord = 0
  for (const paragraph of t.content.split('\n')) {
    lines++ // an explicit newline always starts a line, empty ones included (they still take height)
    let current = ''
    for (const word of paragraph.split(/\s+/).filter(Boolean)) {
      widestWord = Math.max(widestWord, width(word))
      const joined = current ? `${current} ${word}` : word
      if (current && width(joined) > t.box.w) { lines++; current = word } else current = joined
    }
  }
  return { lines, widestWord }
}

/** LAYOUT warnings (non-blocking): canvas overflow, text too wide, overlapping hitboxes.
 *  Approximate but without canvas — catches "blind" positioning bugs before the render. */
export function docLayoutWarnings(doc: Doc): { scope: string; diag: Diagnostic }[] {
  const out: { scope: string; diag: Diagnostic }[] = []
  const W = doc.width, H = doc.height
  const TOL = 8 // overflow tolerance (px) before alerting
  const r0 = (n: number) => Math.round(n)

  // An item whose position is written at RUNTIME — bound to an expression, or dragged directly — has a
  // meaningless static bbox. That rule already existed; what it missed is that it is INHERITED: a label
  // sitting inside a dragged tile is authored around the tile's origin and only lands somewhere real once
  // the tile moves. Measuring it where the file happens to leave it (0,0) reports the whole scene as
  // clipped — the exact noise that would make the pass unusable.
  const dynamicPos = (it: Item) =>
    ('expressions' in it && it.expressions && (it.expressions.x != null || it.expressions.y != null || it.expressions.dx != null || it.expressions.dy != null)) ||
    !!doc.interactors?.some((i) => i.targetId === it.id) // `drag`/`turn`: the pointer decides where it is

  // Every text/image of the scene, paired with the WORLD matrix of its PARENT (the space `itemBBox`
  // reports in) and whether any ancestor is runtime-positioned. Both passes below used to read
  // `doc.layers` top level only — and a group is the only thing a behavior block can animate, so most of
  // a real scene lives inside one and was never measured at all.
  const placed: { it: Text | Image; parent: Transform; dynamic: boolean }[] = []
  const collect = (layers: Layer[], matrix: Transform, dynamic: boolean): void => {
    for (const l of layers) for (const it of l.items) {
      if (isText(it) || isImage(it)) placed.push({ it, parent: matrix, dynamic: dynamic || dynamicPos(it) })
      if (isGroup(it)) collect(it.layers, compose(matrix, it.transform), dynamic || dynamicPos(it))
    }
  }
  collect(doc.layers, IDENTITY, false)

  // (c) TEXT/IMAGE clipped at the canvas edge. Precise to avoid noise: we ignore `path`/groups
  //     (decor that "bleeds" on purpose), anything positioned at runtime (see above), and items PARKED
  //     entirely off-screen ("hidden" pattern).
  for (const { it, parent, dynamic } of placed) {
    if (dynamic || (isText(it) && it.textPath)) continue // path-laid text → §(f), not a box
    const local = itemBBox(doc, it)
    if (!local) continue
    const b = transformBBox(local, parent) // itemBBox is PARENT-space → compose with the ancestors
    const visible = b.maxX > 0 && b.minX < W && b.maxY > 0 && b.minY < H // overlaps the canvas (not parked off-screen)
    const clipped = b.minX < -TOL || b.minY < -TOL || b.maxX > W + TOL || b.maxY > H + TOL
    if (visible && clipped) {
      out.push(warn(`"${itemLabel(it)}" clipped at the canvas edge: bbox [${r0(b.minX)},${r0(b.minY)} -> ${r0(b.maxX)},${r0(b.maxY)}] outside 0,0 -> ${W},${H}`))
    }
  }

  // (d) Text (without `wrap`) whose estimated width makes it OVERFLOW THE CANVAS -> instruction clipped.
  //     (We do NOT compare against `box.w`: without wrap, a text overflows its box harmlessly as long as it
  //      fits in the canvas — it is the canvas edge that clips.)
  for (const { it, parent, dynamic } of placed) {
    if (!isText(it) || it.wrap || it.textPath || dynamic) continue
    const estW = estTextWidth(it)
    const left = it.align === 'left' ? 0 : it.align === 'right' ? it.box.w - estW : it.box.w / 2 - estW / 2
    const m = compose(parent, it.transform) // the text's own world matrix: its baseline runs in ITS space
    const p0 = apply(m, { x: left, y: 0 }), p1 = apply(m, { x: left + estW, y: 0 })
    const wl = Math.min(p0.x, p1.x), wr = Math.max(p0.x, p1.x) // left/right edge of the content in world coords
    if (wr > W + TOL || wl < -TOL) {
      out.push(warn(`text "${it.content.slice(0, 24)}${it.content.length > 24 ? '…' : ''}" overflows the canvas (estimated ~${r0(estW)} px, edge ${r0(wl)}->${r0(wr)} outside 0->${W}) — add "wrap"`))
    }
  }

  // (h) ANY item drawn ENTIRELY outside the canvas. The clipped-at-the-edge pass above deliberately
  //     tolerates straddling (decor bleeds on purpose) and skips items parked off-screen — but "parked"
  //     is only a pattern for something a binding moves back in, and those are excluded as dynamic. A
  //     STATIC item wholly off-canvas is never intentional: it is a coordinate mistake, and until now
  //     nothing said so for a shape or a group. Measured on a model-written board: the eighth token was
  //     laid out past the edge and the whole chain stayed quiet.
  //     Two things this must NOT flag, both measured on a real corpus before the rule was let out:
  //       • an item PARKED off the TOP-LEFT corner on purpose (`at -999,-999` for a payload holder,
  //         `-600,-600` for hidden labels) — the idiom is real, used in 3 of 58 activities measured, and
  //         its signature is that BOTH axes are negative. A mistake overshoots one edge;
  //       • a DEGENERATE bbox lying along an edge (a hairline rule at y=0 spans `0,0 -> 760,0`), which
  //         is on the canvas, not off it — so compare strictly, with the same tolerance as the rest.
  const parked = (b: { maxX: number; maxY: number }) => b.maxX < 0 && b.maxY < 0
  const offCanvas = (b: { minX: number; minY: number; maxX: number; maxY: number }) =>
    (b.maxX < -TOL || b.minX > W + TOL || b.maxY < -TOL || b.minY > H + TOL) && !parked(b)
  const reportOffCanvas = (items: Item[], matrix: Transform, dynamic: boolean): void => {
    for (const it of items) {
      const isDynamic = dynamic || dynamicPos(it)
      if (!isDynamic && !(isText(it) && it.textPath)) {
        const local = itemBBox(doc, it)
        const b = local && transformBBox(local, matrix)
        if (b && offCanvas(b)) {
          // Report the OUTERMOST offender: a group off-canvas takes its whole content with it, and one
          // line about the group is the fix, where one per child is noise.
          out.push(warn(`"${itemLabel(it)}" is drawn entirely off-canvas: bbox [${r0(b.minX)},${r0(b.minY)} -> ${r0(b.maxX)},${r0(b.maxY)}], canvas 0,0 -> ${W},${H}. Nothing of it is visible.`))
          continue
        }
      }
      if (isGroup(it)) for (const l of it.layers) reportOffCanvas(l.items, compose(matrix, it.transform), isDynamic)
    }
  }
  for (const l of doc.layers) reportOffCanvas(l.items, IDENTITY, false)

  // (g) WRAPPED text taller than its box. Pass (d) skips `wrap` — rightly, since wrapping cannot overflow
  //     the box horizontally — but that left wrapped text unmeasured entirely, and what it DOES overflow is
  //     the box's height. Same visible defect: an instruction spilling out of its frame is the first thing
  //     an eye catches, and the reason a whole activity had to be re-read by a multimodal model.
  for (const { it } of placed) {
    if (!isText(it) || !it.wrap || it.textPath) continue
    const { lines, widestWord } = wrapMetrics(it)
    const label = `${it.content.slice(0, 24).replace(/\n/g, ' ')}${it.content.length > 24 ? '…' : ''}`
    const tall = lines * it.size * it.lineHeight
    if (tall > it.box.h + TOL) {
      out.push(warn(`text "${label}" overflows its box: ~${lines} wrapped line(s) ≈ ${r0(tall)} px for a box ${r0(it.box.h)} px tall — raise the box height, shorten the text, or reduce the size`))
    }
    if (widestWord > it.box.w + TOL) {
      out.push(warn(`text "${label}" has a word too wide for its box (~${r0(widestWord)} px > ${r0(it.box.w)} px) — a single word cannot be broken, so it spills past the frame whatever "wrap" says`))
    }
  }

  // (f) Text laid ALONG a path whose estimated run is longer than the path -> trailing glyphs dropped at
  //     render (mirrors the canvas-overflow warning, but for the curve). Position-independent -> recurse.
  const pathTexts: Text[] = []
  const walkPathTexts = (layers: Layer[]) => { for (const l of layers) for (const it of l.items) { if (isText(it) && it.textPath) pathTexts.push(it); else if (isGroup(it)) walkPathTexts(it.layers) } }
  walkPathTexts(doc.layers)
  for (const it of pathTexts) {
    const L = makePathSampler(it.textPath!.path).length
    if (L <= 0) continue
    const advance = (it.weight && it.weight >= 700 ? 0.56 : 0.52) * it.size // same metric as estTextWidth
    const glyphs = [...it.content].length
    const eff = Math.max(advance + (it.textPath!.spacing ?? 0), 1) // mirror the renderer's per-glyph floor
    const estW = glyphs * eff
    if (estW > L + TOL) out.push(warn(`text "${it.content.slice(0, 24)}${it.content.length > 24 ? '…' : ''}" overflows its path (~${r0(estW)}px > ${r0(L)}px) — trailing glyphs are dropped`))
  }

  // (e) Drop zones (`hitbox`) that overlap -> ambiguous drop.
  const zones: { name: string; b: NonNullable<ReturnType<typeof dropZoneBounds>> }[] = []
  const collectZones = (layers: Layer[]) => {
    for (const l of layers) for (const it of l.items) {
      if (isGroup(it) && it.hitbox && it.name) { const b = dropZoneBounds(doc, it.name); if (b) zones.push({ name: it.name, b }) }
      if (isGroup(it)) collectZones(it.layers)
    }
  }
  collectZones(doc.layers)
  for (let i = 0; i < zones.length; i++) for (let j = i + 1; j < zones.length; j++) {
    if (bboxIntersects(zones[i].b, zones[j].b)) out.push(warn(`overlapping hitboxes: "${zones[i].name}" and "${zones[j].name}" -> ambiguous drop`))
  }
  return out
}

/** Semantic lint of a whole Doc (all the scopes) -> diagnostics labeled by scope.
 *  A scope's text contains `object` blocks (outside DSL) -> we lint each region separately and re-project
 *  the lines. `src` = the program SOURCE, when the caller has it (the CLI): the scene scope is then read
 *  from it, so positions and scopes describe the author's file. Without it the scene scope falls back to
 *  the text rebuilt from the Doc — right for the editor, where that rebuilt text IS the file being edited
 *  (cf. CodeEditor.lintFile). Adds the structural warnings (phantom drop zones, dead variables). */
export function lintDoc(doc: Doc, src?: string): { scope: string; diag: Diagnostic }[] {
  const out: { scope: string; diag: Diagnostic }[] = []
  const allVars = allScopeVariables(doc) // computed ONCE (global vars -> known in all the scopes)
  for (const { label, editPath } of scopes(doc)) {
    const ctx = docLintContext(doc, editPath, allVars)
    // The SCENE scope is linted from the SOURCE whenever the caller has it (the CLI does). `scopeProgram`
    // rebuilds a text the author never wrote -- no `scene { … }` block -- so its line numbers are offset by
    // that block's height and its scope is always `scene`, never the `object "X"` the error is really in.
    // Symbols keep the reconstruction: they come from `.flat` libs, whose source is not this program's.
    const regions = src && editPath.length === 0
      ? behaviorRegions(src)
      : scopeRegions(scopeProgram(doc, editPath)).map((r) => ({ scope: label, body: r.body, line: r.line }))
    for (const r of regions)
      for (const d of lint(r.body, ctx)) {
        const shift = r.line - 1
        // The `fix` carries its own positions, relative to the region text exactly like `d.line`. Shift
        // both or the repair lands somewhere else in the file -- and applies cleanly there, silently.
        const fix = d.fix && { ...d.fix, line: d.fix.line + shift, endLine: d.fix.endLine + shift }
        out.push({ scope: r.scope, diag: { ...d, line: d.line + shift, ...(fix ? { fix } : {}) } })
      }
  }
  out.push(...docStructureWarnings(doc))
  out.push(...docModifierWarnings(doc))
  return out
}

/** Lint each stateful channel modifier's TARGET expression with its scope's known names (a symbol's params
 *  included) — so a typo'd `spring rotation "crochetXX"` surfaces as "unknown variable" at `--check` time,
 *  not a silent NaN at runtime. Also flags out-of-range spring damping (clamped at runtime, but worth noting). */
export function docModifierWarnings(doc: Doc): { scope: string; diag: Diagnostic }[] {
  const out: { scope: string; diag: Diagnostic }[] = []
  const allVars = allScopeVariables(doc)
  for (const { label, editPath } of scopes(doc)) {
    const ctx = docLintContext(doc, editPath, allVars)
    const visit = (items: Item[]): void => {
      for (const it of items) {
        if (isPoseable(it) && it.modifiers) for (const ch of EXPR_CHANNELS) {
          const m = it.modifiers[ch]
          if (!m) continue
          for (const d of lint(`${ch} = ${m.target}`, ctx)) out.push({ scope: label, diag: { ...d, line: 1, col: 1, message: `${m.kind} ${ch}: ${d.message}` } })
          if (m.kind === 'spring' && !(m.damping > 0 && m.damping < 1)) out.push({ scope: label, diag: { line: 1, col: 1, severity: 'warning', message: `spring ${ch}: damping ${m.damping} should be in (0,1) — clamped at runtime` } })
        }
        if (isGroup(it)) for (const l of it.layers) visit(l.items) // a group shares the scope; instances are linted on their own symbol pass
      }
    }
    visit(contextLayers(doc, editPath).flatMap((l) => l.items))
    // `velocity()` is valid ONLY in a modifier target (resolved by the player's stateful advance). scopeProgram
    // emits the scope's REGULAR expressions but NOT modifier targets, so any velocity() here is a misuse.
    if (/\bvelocity\s*\(/.test(scopeProgram(doc, editPath)))
      out.push({ scope: label, diag: { line: 1, col: 1, message: 'velocity() is only valid inside a spring/smooth target, not a plain expression' } })
  }
  return out
}

const sev = (d: Diagnostic) => (d.severity === 'warning' ? 'warning' : 'error')

/** Lint report of a Doc ready to display: `''` = no issue, otherwise `[scope] line:col: level: message`.
 *  Pass `src` (the program source) to get positions that point INTO IT rather than into a rebuilt program. */
export function lintDocReport(doc: Doc, src?: string): string {
  return lintDoc(doc, src).map(({ scope, diag }) => `[${scope}] ${diag.line}:${diag.col}: ${sev(diag)}: ${diag.message}`).join('\n')
}

/** `true` if the Doc has at least one ERROR (warnings alone do not block). */
export function docHasErrors(doc: Doc, src?: string): boolean {
  return lintDoc(doc, src).some(({ diag }) => sev(diag) === 'error')
}
