// -----------------------------------------------------------------------------
//  programDoc.ts — PURE bridge Doc <-> "scope program" (text) + lint of a whole Doc.
//
//  Both the editor AND the CLI need to rebuild the DSL text of a scope (to display it,
//  or to lint it) and to assemble the lint context (variables/labels/functions/objects)
//  FROM a Doc — without depending on the React store. Everything lives here, pure and testable:
//   • `scopeProgram`     : Doc fragments -> program text of a scope (round-trip via printUnits);
//   • `docLintContext`   : Doc + scope -> LintContext (known names);
//   • `lintDoc` / report : semantic lint of ALL the scopes of a Doc (scene + symbols).
//  -> the CLI gains a `flatc --check`, the editor stops duplicating the logic.
// -----------------------------------------------------------------------------
import type { Doc, EditFrame, Group, Instance } from '@flatkit/types'
import { printUnits, type Diagnostic } from '@flatkit/engine/dsl'
import { joinScopeProgram, scopeRegions } from './scopeProgram'
import { functionsToUnits, importsToUnits, objectToUnits, timelineToUnits, variablesToUnits } from '@flatkit/engine/scriptDoc'
import { contextLayers, getScopeTimeline, isContainer, isGroup, isText, isImage, isPoseable, isRegion } from '@flatkit/engine/layers'
import { importedFunctions } from '@flatkit/engine/stdlib'
import { EXPR_CHANNELS } from '@flatkit/engine/timeline'
import { objectNames } from '@flatkit/engine/sceneRefs'
import { itemBBox, dropZoneBounds } from '@flatkit/engine/groups'
import { makePathSampler } from '@flatkit/engine/path'
import { bboxIntersects } from '@flatkit/engine/bbox'
import { lint, localVariables, type LintContext } from './lint'
import { parseUnits } from '@flatkit/engine/dsl'
import type { Item, Layer, ParamDef, SymbolDef, Text } from '@flatkit/types'

/** Rebuilds the "program" text of a scope (imports + variables + functions + scene cycle
 *  + one `object "Name" { … }` block per scripted container with a unique name). Pure, round-trip via printUnits. */
export function scopeProgram(doc: Doc, editPath: EditFrame[] = []): string {
  const atRoot = editPath.length === 0
  const items = contextLayers(doc, editPath).flatMap((l) => l.items)
  const nameCount = new Map<string, number>()
  for (const it of items) if (isContainer(it) && it.name) nameCount.set(it.name, (nameCount.get(it.name) ?? 0) + 1)
  const scripted = (it: Group | Instance) => !!doc.interactions?.some((i) => i.targetId === it.id) || !!doc.interactors?.some((i) => i.targetId === it.id) || !!(it.expressions && Object.keys(it.expressions).length)
  const objects = items
    .filter((it): it is Group | Instance => isContainer(it) && !!it.name && nameCount.get(it.name) === 1 && scripted(it))
    .map((it) => ({ name: it.name, body: printUnits(objectToUnits(it.id, doc.interactions, it.expressions, doc.interactors)) }))
  const imports = atRoot ? printUnits(importsToUnits(doc.imports)) : ''
  const funcs = atRoot ? printUnits(functionsToUnits(doc.functions)) : ''
  const globals = atRoot ? printUnits(variablesToUnits(doc.variables)) : ''
  const scene = printUnits(timelineToUnits(getScopeTimeline(doc, editPath)))
  const head = [imports, globals, funcs, scene].filter((t) => t.trim()).join('\n\n')
  return joinScopeProgram(head, objects)
}

/** Lint context of a scope: known names (variables, labels, functions, objects) drawn from the Doc.
 *  `extraVars` = variables assigned in the OTHER scopes (FlatInk variables are GLOBAL -> known
 *  everywhere; avoids a false "unknown variable" on a var written elsewhere, e.g. generated by `match`). */
export function docLintContext(doc: Doc, editPath: EditFrame[] = [], extraVars?: Iterable<string>): LintContext {
  return {
    // A symbol's own `params` (and state params) are injected into its instance scope at runtime, so they are
    // valid variables in ITS `expr` -- add them, but ONLY to that symbol's scope (resolved from `editPath`),
    // never globally, so a param named in symbol A can't mask a real typo of the same name in symbol B.
    variables: [...Object.keys(doc.variables ?? {}), ...(extraVars ?? []), ...scopeSymbolParams(doc, editPath)],
    labels: (getScopeTimeline(doc, editPath)?.labels ?? []).map((l) => l.name),
    functions: [...(doc.functions ?? []).map((f) => f.name), ...importedFunctions(doc.imports).map((f) => f.name)],
    objects: objectNames(contextLayers(doc, editPath)),
  }
}

/** Names exposed as variables by the symbol of `editPath` (its `params` + state params), or `[]` for the
 *  scene scope / an unresolved path. Mirrors the per-instance scope the runtime and `--preview` build. */
function scopeSymbolParams(doc: Doc, editPath: EditFrame[]): string[] {
  const frame = [...editPath].reverse().find((f): f is Extract<EditFrame, { kind: 'symbol' }> => f.kind === 'symbol')
  const sym = frame ? doc.symbols.find((s) => s.id === frame.symbolId) : undefined
  if (!sym) return []
  return [...(sym.params ?? []).map((p) => p.name), ...(sym.states ?? []).map((s) => s.param)]
}

/** All the scopes of a Doc: the scene (root) + each symbol of the library. */
function scopes(doc: Doc): { label: string; editPath: EditFrame[] }[] {
  return [{ label: 'scene', editPath: [] }, ...doc.symbols.map((s) => ({ label: s.name, editPath: [{ kind: 'symbol' as const, symbolId: s.id, name: s.name }] }))]
}

/** Union of the variables ASSIGNED in ALL the scopes (scene + symbols). FlatInk variables are
 *  global -> a var written in one scope is legitimate in the others (cross-scope reads). */
export function allScopeVariables(doc: Doc): string[] {
  const set = new Set<string>()
  for (const { editPath } of scopes(doc))
    for (const r of scopeRegions(scopeProgram(doc, editPath)))
      for (const v of localVariables(parseUnits(r.body).units)) set.add(v)
  return [...set]
}

/** Readable name of an item by id (for the messages). */
function itemNameById(doc: Doc, id: string): string | null {
  let found: string | null = null
  const walk = (layers: { items: import('@flatkit/types').Item[] }[]) => {
    for (const l of layers) for (const it of l.items) {
      if (found) return
      if ('name' in it && it.id === id) { found = it.name ?? null; return }
      if (isGroup(it)) walk(it.layers)
    }
  }
  walk(doc.layers)
  return found
}

const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\-]/g, '\\$&')

/** STRUCTURAL warnings (non-blocking) of a Doc: phantom drop zones, dead variables. */
export function docStructureWarnings(doc: Doc): { scope: string; diag: Diagnostic }[] {
  const out: { scope: string; diag: Diagnostic }[] = []
  // (a) `when dropped on X` whose zone X does not exist (no item named so) -> the handler can never fire.
  const names = new Set(objectNames(doc.layers))
  for (const it of doc.interactions ?? []) {
    if (it.event === 'drop' && it.over && !names.has(it.over)) {
      const who = itemNameById(doc, it.targetId) ?? it.targetId
      out.push({ scope: 'scene', diag: { line: 1, col: 1, severity: 'warning', message: `unknown drop zone "${it.over}" (object "${who}") — no item of the scene carries this name` } })
    }
  }
  // (b) global variable never referenced (declared but not found in any scope) -> probably dead.
  const names0 = Object.keys(doc.variables ?? {})
  if (names0.length) {
    // Modifier targets are NOT emitted into scopeProgram (to avoid double-linting them, cf. docModifierWarnings),
    // so collect them here too — else a global used ONLY by a `spring`/`smooth` target reads as "never used".
    const modTargets: string[] = []
    const collectMods = (items: Item[]): void => {
      for (const it of items) {
        if (isPoseable(it) && it.modifiers) for (const ch of EXPR_CHANNELS) { const mm = it.modifiers[ch]; if (mm) modTargets.push(mm.target) }
        if (isGroup(it)) for (const l of it.layers) collectMods(l.items)
      }
    }
    for (const l of doc.layers) collectMods(l.items)
    for (const s of doc.symbols ?? []) for (const l of s.layers) collectMods(l.items)
    const allText = [...scopes(doc).map(({ editPath }) => scopeProgram(doc, editPath)), ...modTargets].join('\n')
    for (const name of names0) {
      const m = allText.match(new RegExp(`(?<![\\w-])${escapeRe(name)}(?![\\w-])`, 'g'))
      if ((m?.length ?? 0) <= 1) out.push({ scope: 'scene', diag: { line: 1, col: 1, severity: 'warning', message: `global variable "${name}" never used (declared, but neither read nor written)` } })
    }
  }
  // (c) raw `time` in a channel expression + a SHORT looping timeline → ambient motion JUMPS on each loop
  //     (`time = frame/fps` resets to 0 every `durationFrames`). The monotone `clock` never wraps.
  const dur = doc.timeline?.durationFrames ?? 60
  const fps = doc.timeline?.fps ?? 24
  if (dur <= 120) { // ≤ 5 s @24fps: short enough that the reset is visible as a periodic jump
    let usesTime = false
    const scan = (layers: Layer[]) => {
      for (const l of layers) for (const it of l.items) {
        if (isPoseable(it) && it.expressions) for (const k in it.expressions) if (/\btime\b/.test(it.expressions[k as keyof typeof it.expressions] ?? '')) usesTime = true
        if (isGroup(it)) scan(it.layers)
      }
    }
    scan(doc.layers)
    if (usesTime) {
      const secs = Math.round((dur / fps) * 10) / 10
      out.push(warn(`a channel expression uses \`time\`, but the timeline loops every ${secs}s (durationFrames ${dur}) — \`time\` resets each loop, so the motion jumps. Use the monotone \`clock\` (never wraps), drive it by \`frame/${dur}\`, or set a longer \`timeline\`.`))
    }
  }
  out.push(...docPaintParamWarnings(doc))
  out.push(...docLayoutWarnings(doc))
  return out
}

/** A scope's declared `color` param names (the only params usable as a paint color). */
const colorParamNames = (params?: ParamDef[]): Set<string> => new Set((params ?? []).filter((p) => p.type === 'color').map((p) => p.name))

/**
 * A `color` param used as a paint (`fill`/`stroke`, a gradient **stop** `0:teinte@…`, or a `tint`) that the
 * owning symbol does NOT declare → a SILENT "dead recolor" (it falls back to the literal hex, the picker does
 * nothing). Warns per scope, with the param scoped to ITS symbol (the scene declares none). Mirrors how the
 * lint now knows a symbol's params in its `expr`. Non-blocking (a warning), so it never breaks a build.
 */
export function docPaintParamWarnings(doc: Doc): { scope: string; diag: Diagnostic }[] {
  const out: { scope: string; diag: Diagnostic }[] = []
  const checkScope = (scope: string, layers: Layer[], known: Set<string>) => {
    const flag = (param: string, where: string, who?: string) => {
      if (known.has(param)) return
      const hint = known.size ? `declared color params: ${[...known].join(', ')}` : 'this scope declares no color params'
      out.push({ scope, diag: { line: 1, col: 1, severity: 'warning', message: `unknown color param "${param}" in ${where}${who ? ` (${who})` : ''} — ${hint}` } })
    }
    const visit = (it: Item) => {
      const who = 'name' in it ? it.name : undefined
      if (isRegion(it)) {
        if (it.fillParam) flag(it.fillParam, 'a fill', who)
        if (it.strokeParam) flag(it.strokeParam, 'a stroke', who)
        const stops = it.paint && it.paint.type !== 'solid' ? it.paint.stops : []
        for (const s of stops) if (s.param) flag(s.param, 'a gradient stop', who)
      }
      if (isPoseable(it) && it.tint?.param) flag(it.tint.param, 'a tint', who)
      if (isGroup(it)) for (const l of it.layers) for (const c of l.items) visit(c) // a group is the same scope; an instance is a separate symbol (linted on its own pass)
    }
    for (const l of layers) for (const it of l.items) visit(it)
  }
  checkScope('scene', doc.layers, new Set())
  for (const s of doc.symbols) checkScope(s.name, s.layers, colorParamNames((s as SymbolDef).params))
  return out
}

const warn = (message: string): { scope: string; diag: Diagnostic } => ({ scope: 'scene', diag: { line: 1, col: 1, severity: 'warning', message } })
const itemLabel = (it: Item): string => ('name' in it && it.name ? it.name : 'kind' in it ? it.kind : 'path')
/** Estimated width of the longest line (approximate metric, without canvas). */
function estTextWidth(t: Text): number {
  const advance = (t.weight && t.weight >= 700 ? 0.56 : 0.52) * t.size // mean advance of a proportional glyph
  let longest = 0
  for (const line of t.content.split('\n')) longest = Math.max(longest, line.length)
  return longest * advance
}

/** LAYOUT warnings (non-blocking): canvas overflow, text too wide, overlapping hitboxes.
 *  Approximate but without canvas — catches "blind" positioning bugs before the render. */
export function docLayoutWarnings(doc: Doc): { scope: string; diag: Diagnostic }[] {
  const out: { scope: string; diag: Diagnostic }[] = []
  const W = doc.width, H = doc.height
  const TOL = 8 // overflow tolerance (px) before alerting
  const r0 = (n: number) => Math.round(n)

  // (c) TEXT/IMAGE clipped at the canvas edge. Precise to avoid noise: we ignore `path`/groups
  //     (decor that "bleeds" on purpose), objects driven by an expression (dynamic position ->
  //     misleading static bbox), and items PARKED entirely off-screen ("hidden" pattern).
  const dynamicPos = (it: Item) => 'expressions' in it && it.expressions && (it.expressions.x != null || it.expressions.y != null)
  for (const layer of doc.layers) {
    for (const it of layer.items) {
      if (!(isText(it) || isImage(it)) || dynamicPos(it) || (isText(it) && it.textPath)) continue // path-laid text → §(f), not a box
      const b = itemBBox(doc, it)
      if (!b) continue
      const visible = b.maxX > 0 && b.minX < W && b.maxY > 0 && b.minY < H // overlaps the canvas (not parked off-screen)
      const clipped = b.minX < -TOL || b.minY < -TOL || b.maxX > W + TOL || b.maxY > H + TOL
      if (visible && clipped) {
        out.push(warn(`"${itemLabel(it)}" clipped at the canvas edge: bbox [${r0(b.minX)},${r0(b.minY)} -> ${r0(b.maxX)},${r0(b.maxY)}] outside 0,0 -> ${W},${H}`))
      }
    }
  }

  // (d) Text (without `wrap`) whose estimated width makes it OVERFLOW THE CANVAS -> instruction clipped.
  //     (We do NOT compare against `box.w`: without wrap, a text overflows its box harmlessly as long as it
  //      fits in the canvas — it is the canvas edge that clips.) Top-level only (x = world).
  for (const it of doc.layers.flatMap((l) => l.items)) {
    if (!isText(it) || it.wrap || it.textPath || dynamicPos(it)) continue
    const estW = estTextWidth(it)
    const left = it.align === 'left' ? 0 : it.align === 'right' ? it.box.w - estW : it.box.w / 2 - estW / 2
    const wl = it.transform.e + left, wr = wl + estW // left/right edge of the content in world coords
    if (wr > W + TOL || wl < -TOL) {
      out.push(warn(`text "${it.content.slice(0, 24)}${it.content.length > 24 ? '…' : ''}" overflows the canvas (estimated ~${r0(estW)} px, edge ${r0(wl)}->${r0(wr)} outside 0->${W}) — add "wrap"`))
    }
  }

  // (f) Text laid ALONG a path whose estimated run is longer than the path -> trailing glyphs dropped at
  //     render (mirrors the canvas-overflow warning, but for the curve). Position-independent -> recurse.
  const pathTexts: Text[] = []
  const walkPathTexts = (layers: Layer[]) => { for (const l of layers) for (const it of l.items) { if (isText(it) && it.textPath) pathTexts.push(it); else if (isGroup(it)) walkPathTexts(it.layers) } }
  walkPathTexts(doc.layers)
  for (const it of pathTexts) {
    const L = makePathSampler(it.textPath!.path).length
    if (L <= 0) continue
    const advance = (it.weight && it.weight >= 700 ? 0.56 : 0.52) * it.size // same metric as estTextWidth
    const glyphs = [...it.content].length
    const eff = Math.max(advance + (it.textPath!.spacing ?? 0), 1) // mirror the renderer's per-glyph floor
    const estW = glyphs * eff
    if (estW > L + TOL) out.push(warn(`text "${it.content.slice(0, 24)}${it.content.length > 24 ? '…' : ''}" overflows its path (~${r0(estW)}px > ${r0(L)}px) — trailing glyphs are dropped`))
  }

  // (e) Drop zones (`hitbox`) that overlap -> ambiguous drop.
  const zones: { name: string; b: NonNullable<ReturnType<typeof dropZoneBounds>> }[] = []
  const collectZones = (layers: Layer[]) => {
    for (const l of layers) for (const it of l.items) {
      if (isGroup(it) && it.hitbox && it.name) { const b = dropZoneBounds(doc, it.name); if (b) zones.push({ name: it.name, b }) }
      if (isGroup(it)) collectZones(it.layers)
    }
  }
  collectZones(doc.layers)
  for (let i = 0; i < zones.length; i++) for (let j = i + 1; j < zones.length; j++) {
    if (bboxIntersects(zones[i].b, zones[j].b)) out.push(warn(`overlapping hitboxes: "${zones[i].name}" and "${zones[j].name}" -> ambiguous drop`))
  }
  return out
}

/** Semantic lint of a whole Doc (all the scopes) -> diagnostics labeled by scope.
 *  The scope program contains `object` blocks (outside DSL) -> we lint each region
 *  separately and re-project the lines (like the editor, cf. CodeEditor.lintFile).
 *  Adds the structural warnings (phantom drop zones, dead variables). */
export function lintDoc(doc: Doc): { scope: string; diag: Diagnostic }[] {
  const out: { scope: string; diag: Diagnostic }[] = []
  const allVars = allScopeVariables(doc) // computed ONCE (global vars -> known in all the scopes)
  for (const { label, editPath } of scopes(doc)) {
    const ctx = docLintContext(doc, editPath, allVars)
    for (const r of scopeRegions(scopeProgram(doc, editPath))) for (const d of lint(r.body, ctx)) out.push({ scope: label, diag: { ...d, line: d.line + r.line - 1 } })
  }
  out.push(...docStructureWarnings(doc))
  out.push(...docModifierWarnings(doc))
  return out
}

/** Lint each stateful channel modifier's TARGET expression with its scope's known names (a symbol's params
 *  included) — so a typo'd `spring rotation "crochetXX"` surfaces as "unknown variable" at `--check` time,
 *  not a silent NaN at runtime. Also flags out-of-range spring damping (clamped at runtime, but worth noting). */
export function docModifierWarnings(doc: Doc): { scope: string; diag: Diagnostic }[] {
  const out: { scope: string; diag: Diagnostic }[] = []
  const allVars = allScopeVariables(doc)
  for (const { label, editPath } of scopes(doc)) {
    const ctx = docLintContext(doc, editPath, allVars)
    const visit = (items: Item[]): void => {
      for (const it of items) {
        if (isPoseable(it) && it.modifiers) for (const ch of EXPR_CHANNELS) {
          const m = it.modifiers[ch]
          if (!m) continue
          for (const d of lint(`${ch} = ${m.target}`, ctx)) out.push({ scope: label, diag: { ...d, line: 1, col: 1, message: `${m.kind} ${ch}: ${d.message}` } })
          if (m.kind === 'spring' && !(m.damping > 0 && m.damping < 1)) out.push({ scope: label, diag: { line: 1, col: 1, severity: 'warning', message: `spring ${ch}: damping ${m.damping} should be in (0,1) — clamped at runtime` } })
        }
        if (isGroup(it)) for (const l of it.layers) visit(l.items) // a group shares the scope; instances are linted on their own symbol pass
      }
    }
    visit(contextLayers(doc, editPath).flatMap((l) => l.items))
  }
  return out
}

const sev = (d: Diagnostic) => (d.severity === 'warning' ? 'warning' : 'error')

/** Lint report of a Doc ready to display: `''` = no issue, otherwise `[scope] line:col: level: message`. */
export function lintDocReport(doc: Doc): string {
  return lintDoc(doc).map(({ scope, diag }) => `[${scope}] ${diag.line}:${diag.col}: ${sev(diag)}: ${diag.message}`).join('\n')
}

/** `true` if the Doc has at least one ERROR (warnings alone do not block). */
export function docHasErrors(doc: Doc): boolean {
  return lintDoc(doc).some(({ diag }) => sev(diag) === 'error')
}
