// Generates packages/engine/src/stdlib.generated.ts: pre-compiles the stdlib packages
// (text DSL → FuncDef[] AST) so the RUNTIME does not bundle the DSL parser (dsl.ts ~15 KiB).
//
//   pnpm --filter @flatkit/engine gen:stdlib
//
// The sources ⇄ generated sync is guaranteed by stdlib.generated.test.ts (it fails if the
// sources are edited without regenerating).

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import type { FuncDef } from '@flatkit/types'
import { PACKAGE_SOURCES } from '../src/stdlib.sources'
import { parseUnits } from '../src/dsl'
import { unitsToFunctions } from '../src/scriptDoc'

const funcs: Record<string, FuncDef[]> = {}
for (const [name, src] of Object.entries(PACKAGE_SOURCES)) {
  funcs[name] = unitsToFunctions(parseUnits(src).units)
}

const out = `// ─────────────────────────────────────────────────────────────────────────────
//  stdlib.generated.ts — AUTO-GENERATED by scripts/gen-stdlib.ts — DO NOT EDIT BY HAND.
//  Pre-compiled stdlib packages (DSL → AST). The runtime consumes them directly, without a parser.
//  Regenerate: pnpm --filter @flatkit/engine gen:stdlib  (then verified by stdlib.generated.test.ts).
// ─────────────────────────────────────────────────────────────────────────────
import type { FuncDef } from '@flatkit/types'

export const PACKAGE_FUNCS: Record<string, FuncDef[]> = ${JSON.stringify(funcs, null, 2)}
`

const dest = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'stdlib.generated.ts')
writeFileSync(dest, out, 'utf8')
console.log(`stdlib.generated.ts — ${Object.keys(funcs).length} packages, ${Object.values(funcs).reduce((n, f) => n + f.length, 0)} functions`)
