import { describe, it, expect } from 'vitest'
import { Client } from '@modelcontextprotocol/sdk/client/index.js'
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js'
import { buildServer } from './server.ts'
import type { ForgeClient } from './forgeClient.ts'
import { readFileSync } from 'node:fs'

// FAKE forge client -> we test the MCP wiring (handshake, tools, routing), not the real forge.
const fake: ForgeClient = {
  base: 'http://forge.test',
  hasKey: true,
  searchAssets: async (q) => ({ ok: true, query: q, assets: [{ name: 'soap', use: { dsl: 'image "soap" 64 64 at 0,0' } }] }),
  getAsset: async (name) => ({ ok: true, asset: { name } }),
  check: async () => ({ ok: true }),
  preview: async () => ({ ok: true, png: 'data:image/png;base64,QQ==', width: 50, height: 50 }),
  publish: async () => ({ ok: true, url: 'http://forge.test/p/abc' }),
  previewSymbolFrames: async () => ({ ok: true, engine: 'player', width: 64, height: 64, frames: ['data:image/png;base64,QQ==', 'data:image/png;base64,QQ=='] }),
}

describe('MCP server (in-memory transport)', () => {
  it('handshake + 6 tools; search/preview route to the client', async () => {
    const [ct, st] = InMemoryTransport.createLinkedPair()
    const client = new Client({ name: 'test', version: '0' })
    await Promise.all([buildServer(fake).connect(st), client.connect(ct)])

    const tools = await client.listTools()
    expect(tools.tools.map((t) => t.name).sort()).toEqual(['check_scene', 'describe_scene', 'get_asset', 'preview_scene', 'preview_symbol', 'publish_scene', 'search_assets'])

    const s = await client.callTool({ name: 'search_assets', arguments: { query: 'soap' } })
    expect(JSON.stringify(s.content)).toContain('soap')

    // preview -> PNG image block (visual iteration)
    const p = await client.callTool({ name: 'preview_scene', arguments: { source: 'size 50 50', library: ['soap'] } })
    const blocks = p.content as Array<{ type: string; mimeType?: string }>
    expect(blocks.some((b) => b.type === 'image' && b.mimeType === 'image/png')).toBe(true)

    // preview_symbol -> one image block PER requested frame (iterating on a symbol asset)
    const ps = await client.callTool({ name: 'preview_symbol', arguments: { lib: 'symbol "X" {}', frames: [0, 4], engine: 'player' } })
    const psBlocks = ps.content as Array<{ type: string; mimeType?: string }>
    expect(psBlocks.filter((b) => b.type === 'image').length).toBe(2)

    await client.close()
  })
})

// An agent could compile, render and publish — and had nowhere to LEARN the language, while the compiler
// package ships the cards, the guides and the system prompts. They are resources now.
describe('MCP server — the language it serves', () => {
  const connect = async () => {
    const [ct, st] = InMemoryTransport.createLinkedPair()
    const client = new Client({ name: 'test', version: '0' })
    await Promise.all([buildServer(fake).connect(st), client.connect(ct)])
    return client
  }

  it('serves the two reference cards, generated by the INSTALLED compiler', async () => {
    const client = await connect()
    const uris = (await client.listResources()).resources.map((r) => r.uri)
    expect(uris).toContain('flatink://card/language')
    expect(uris).toContain('flatink://card/drawing')
    const card = await client.readResource({ uri: 'flatink://card/drawing' })
    expect(String((card.contents[0] as { text?: string }).text)).toContain('draw <0..1>') // the current grammar, not a snapshot
  })

  it('serves the guides and the system prompts the compiler publishes', async () => {
    const client = await connect()
    const uris = (await client.listResources()).resources.map((r) => r.uri)
    expect(uris).toContain('flatink://docs/behavior-and-interactions')
    expect(uris).toContain('flatink://prompt/flatink-core')
    const guide = await client.readResource({ uri: 'flatink://docs/behavior-and-interactions' })
    expect(String((guide.contents[0] as { text?: string }).text)).toContain('## Interactors')
  })

  it('`describe_scene` answers what a program DOES, locally — procedures included', async () => {
    const client = await connect()
    const src = [
      'size 100 100', 'var score = 0',
      'fn win() {', '  send "completed"', '}',
      'scene { layer "L" { group "B" at 50,50 { layer "c" { circle 0 0 9 fill #111111 } } } }',
      'object "B" {', '  when clicked {', '    win()', '  }', '}',
    ].join('\n')
    const r = await client.callTool({ name: 'describe_scene', arguments: { source: src } })
    const out = JSON.stringify(r.content)
    expect(out).toContain('completed') // the event, though no `send` appears in the object block
    expect(out).toContain('score')
  })

  it('reports its OWN version, not a literal that drifts', async () => {
    const client = await connect()
    const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8')) as { version: string }
    expect(client.getServerVersion()?.version).toBe(pkg.version)
  })
})
