// FlatInk MCP server (stdio transport): exposes the asset library + the forge's compile/preview/publish
// as TOOLS for LLM agents. Configured via env: FORGE_URL (default localhost:7712), FORGE_API_KEY.
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { z } from 'zod'
import { createRequire } from 'node:module'
import { readFileSync } from 'node:fs'
// One dependency, one supported surface: the compiler re-exports the parser, so the MCP never reaches
// into the engine's subpaths (which the published package maps as a wildcard).
import { languageCard, drawingCard, docToManifest, parseProgramFull } from '@flatkit/compiler'
import { createForgeClient } from './forgeClient.ts'

const client = createForgeClient(process.env.FORGE_URL ?? 'http://localhost:7712', process.env.FORGE_API_KEY ?? '')

const text = (o: unknown) => ({ content: [{ type: 'text' as const, text: typeof o === 'string' ? o : JSON.stringify(o, null, 2) }] })
const fail = (msg: string) => ({ content: [{ type: 'text' as const, text: msg }], isError: true })

const require_ = createRequire(import.meta.url)
/** Our own version, read rather than retyped: the literal here said 0.1.0 while the package said 0.2.0,
 *  and the number a client sees in the handshake is the one it would quote in a bug report. `../package.json`
 *  resolves from `src/` in dev and from `dist/` once built — the package root either way. */
const VERSION = (require_('../package.json') as { version: string }).version

/**
 * The language, as MCP RESOURCES. An agent connecting to this server could compile, render and publish —
 * and had nowhere to learn the DSL from, while the compiler package ships exactly that. Two reference
 * cards (pure functions, always in step with the installed version) and the guides/prompts it publishes.
 * A file that cannot be resolved is skipped rather than failing the handshake: the docs are shipped by a
 * dependency, and a client with an odd install should still get its tools.
 */
const CARDS = [
  { slug: 'language', title: 'FlatInk behavior reference (the card)', body: () => languageCard(), what: 'events, actions, expressions, interactors — the BEHAVIOR half' },
  { slug: 'drawing', title: 'FlatInk composition reference (the card)', body: () => drawingCard(), what: 'shapes, paints, filters, text, clipping — the SCENE half' },
]
const shipped = (subpath: string): string | null => {
  try { return readFileSync(require_.resolve(`@flatkit/compiler/${subpath}`), 'utf8') } catch { return null }
}
const GUIDES = ['getting-started', 'scene-and-drawing', 'animating-symbols', 'behavior-and-interactions',
  'expressions-and-stdlib', 'tooling', 'host-integration', 'embedding-fonts', 'dsl-gotchas']
const PROMPTS = ['flatink-core', 'flatink-lite', 'role-coder', 'role-motion-designer', 'role-asset-creator']

export function buildServer(c: typeof client = client): McpServer {
  const server = new McpServer({ name: 'flatink', version: VERSION })

  for (const card of CARDS) {
    server.registerResource(`card-${card.slug}`, `flatink://card/${card.slug}`, {
      title: card.title,
      description: `Compact reference an agent can hold in context — ${card.what}. Generated by the installed compiler, so it never drifts from the version that will check your source.`,
      mimeType: 'text/markdown',
    }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: 'text/markdown', text: card.body() }] }))
  }
  for (const name of GUIDES) {
    const body = shipped(`docs/${name}.md`)
    if (body === null) continue
    server.registerResource(`guide-${name}`, `flatink://docs/${name}`, {
      title: `FlatInk guide: ${name.replace(/-/g, ' ')}`,
      description: 'The published guide, shipped with the compiler — the long form behind the cards.',
      mimeType: 'text/markdown',
    }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: 'text/markdown', text: body }] }))
  }
  for (const name of PROMPTS) {
    const body = shipped(`prompts/${name}.md`)
    if (body === null) continue
    server.registerResource(`prompt-${name}`, `flatink://prompt/${name}`, {
      title: `FlatInk system prompt: ${name}`,
      description: 'A ready-made system prompt for writing FlatInk (core = the full grammar, lite = the compact one, role-* = a working posture).',
      mimeType: 'text/markdown',
    }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: 'text/markdown', text: body }] }))
  }

  server.registerTool('describe_scene', {
    description:
      'What does this program DO? Parses a `.flatink` source LOCALLY (no forge round-trip) and returns its manifest: ' +
      'the named objects with the contract each carries (events handled, channels driven, variables read), the state variables, ' +
      'the functions, and the `send` events it emits — including the ones emitted from inside a procedure or an `if` body, ' +
      'which reading the text for `send` would miss. Use it to check what you just wrote, or to decide whether a fragment ' +
      'is allowed to do what it does.',
    inputSchema: { source: z.string().describe('.flatink DSL source') },
  }, async ({ source }) => {
    try {
      return text(docToManifest(parseProgramFull(source) as never))
    } catch (e) {
      return fail('describe failed: ' + (e instanceof Error ? e.message : String(e)))
    }
  })

  server.registerTool('search_assets', {
    description:
      'Search the FlatInk library for turnkey assets (clipart) by natural-language query. ' +
      'Returns, per asset: `name`, dimensions, tags, and a ready-to-paste RECIPE -- `use.dsl` (the `image "<name>" <w> <h> at <x>,<y>` line) ' +
      'and `use.publish.library` (the name to pass in `library:[...]` when previewing/publishing).',
    inputSchema: {
      query: z.string().describe('natural-language query, e.g. "musical instrument", "renewable energy"'),
      category: z.string().optional().describe('category filter (animals, objects, nature, buildings, ...)'),
      view: z.string().optional().describe('orientation filter (front, side, three-quarter, top, back, flat)'),
      style: z.string().optional().describe('graphic-style / collection filter, e.g. "engraving" (antique monochrome) or "paper-theater" (flat color clipart)'),
      limit: z.number().int().min(1).max(50).optional(),
    },
  }, async ({ query, category, view, style, limit }) => text(await c.searchAssets(query, { category, view, style, limit })))

  server.registerTool('get_asset', {
    description: 'Look up a library asset by its exact `name` (dimensions, tags, description, recipe).',
    inputSchema: { name: z.string() },
  }, async ({ name }) => text(await c.getAsset(name)))

  server.registerTool('check_scene', {
    description: 'Validate a `.flatink` DSL source (compile without rendering) -> { ok, errors, warnings }.',
    inputSchema: {
      source: z.string().describe('.flatink DSL source'),
      library: z.array(z.string()).optional().describe('names of library assets referenced by `image "<name>"` in the source'),
    },
  }, async ({ source, library }) => text(await c.check(source, library)))

  server.registerTool('preview_scene', {
    description: 'Compile + RENDER a DSL source to PNG and return the image (to iterate visually). `library` assets are inlined server-side.',
    inputSchema: {
      source: z.string(),
      library: z.array(z.string()).optional(),
      frame: z.number().int().optional().describe('timeline frame to render (default 0)'),
      scale: z.number().optional(),
    },
  }, async ({ source, library, frame, scale }) => {
    const r = (await c.preview(source, library, { frame, scale })) as { ok?: boolean; png?: string; width?: number; height?: number; errors?: unknown; error?: unknown }
    if (!r.ok || !r.png) return fail('preview failed: ' + JSON.stringify(r.errors ?? r.error ?? r))
    return {
      content: [
        { type: 'image' as const, data: r.png.replace(/^data:image\/png;base64,/, ''), mimeType: 'image/png' },
        { type: 'text' as const, text: `rendered ${r.width}x${r.height}` },
      ],
    }
  })

  server.registerTool('preview_symbol', {
    description:
      'Render N frames of ONE symbol from a `.flat` library and return the images -- to ITERATE on a symbol ' +
      'asset WITHOUT storing anything. `engine:"player"` animates reactive modifiers (spring/velocity) and ' +
      'sub-loops; `"flatc"` (default) freezes those modifiers but honors `scale`. Set states / params / ' +
      'colors via `set` (e.g. { "state": "spin", "body": "#E94F4F" }).',
    inputSchema: {
      lib: z.string().describe('contents of the .flat file (symbol library)'),
      symbol: z.string().optional().describe('symbol name (default: the first in the lib)'),
      frames: z.array(z.number().int().min(0)).min(1).describe('frame numbers to render (<= 24)'),
      set: z.record(z.string(), z.union([z.string(), z.number()])).optional().describe('states / params / recolor to apply'),
      engine: z.enum(['flatc', 'player']).optional().describe('"player" to animate spring/velocity; "flatc" by default'),
      scale: z.number().optional().describe('resolution factor (engine "flatc" only)'),
    },
  }, async ({ lib, symbol, frames, set, engine, scale }) => {
    const r = (await c.previewSymbolFrames(lib, { symbol, frames, set, engine, scale })) as
      { ok?: boolean; engine?: string; width?: number; height?: number; frames?: string[]; errors?: unknown; error?: unknown }
    if (!r.ok || !r.frames?.length) return fail('preview-symbol failed: ' + JSON.stringify(r.errors ?? r.error ?? r))
    return {
      content: [
        ...r.frames.map((f) => ({ type: 'image' as const, data: f.replace(/^data:image\/png;base64,/, ''), mimeType: 'image/png' as const })),
        { type: 'text' as const, text: `${r.frames.length} frame(s) - ${r.width}x${r.height} - engine ${r.engine}` },
      ],
    }
  })

  server.registerTool('publish_scene', {
    description: 'Publish a scene (compile + store) and return its public URL (/p/:id). `library` assets are inlined.',
    inputSchema: {
      source: z.string(),
      library: z.array(z.string()).optional(),
      title: z.string().optional(),
    },
  }, async ({ source, library, title }) => {
    const r = (await c.publish(source, { library, title })) as { ok?: boolean; url?: string; errors?: unknown; error?: unknown }
    if (!r.ok || !r.url) return fail('publish failed: ' + JSON.stringify(r.errors ?? r.error ?? r))
    return text(r)
  })

  return server
}

// stdio startup (except in tests, where we import buildServer directly).
if (process.env.NODE_ENV !== 'test') {
  const server = buildServer()
  await server.connect(new StdioServerTransport())
}
